package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Annotation generated by hbm2java
 */
public class Annotation implements java.io.Serializable {

	private int id;
	private int editor;
	private String text;
	private String changelog;
	private Date created;

	public Annotation() {
	}

	public Annotation(int id, int editor) {
		this.id = id;
		this.editor = editor;
	}

	public Annotation(int id, int editor, String text, String changelog,
			Date created) {
		this.id = id;
		this.editor = editor;
		this.text = text;
		this.changelog = changelog;
		this.created = created;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getEditor() {
		return this.editor;
	}

	public void setEditor(int editor) {
		this.editor = editor;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public String getChangelog() {
		return this.changelog;
	}

	public void setChangelog(String changelog) {
		this.changelog = changelog;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

}
