package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * Application generated by hbm2java
 */
public class Application implements java.io.Serializable {

	private int id;
	private int owner;
	private String name;
	private String oauthId;
	private String oauthSecret;
	private String oauthRedirectUri;

	public Application() {
	}

	public Application(int id, int owner, String name, String oauthId,
			String oauthSecret) {
		this.id = id;
		this.owner = owner;
		this.name = name;
		this.oauthId = oauthId;
		this.oauthSecret = oauthSecret;
	}

	public Application(int id, int owner, String name, String oauthId,
			String oauthSecret, String oauthRedirectUri) {
		this.id = id;
		this.owner = owner;
		this.name = name;
		this.oauthId = oauthId;
		this.oauthSecret = oauthSecret;
		this.oauthRedirectUri = oauthRedirectUri;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getOwner() {
		return this.owner;
	}

	public void setOwner(int owner) {
		this.owner = owner;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getOauthId() {
		return this.oauthId;
	}

	public void setOauthId(String oauthId) {
		this.oauthId = oauthId;
	}

	public String getOauthSecret() {
		return this.oauthSecret;
	}

	public void setOauthSecret(String oauthSecret) {
		this.oauthSecret = oauthSecret;
	}

	public String getOauthRedirectUri() {
		return this.oauthRedirectUri;
	}

	public void setOauthRedirectUri(String oauthRedirectUri) {
		this.oauthRedirectUri = oauthRedirectUri;
	}

}
