package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * AreaTagId generated by hbm2java
 */
public class AreaTagId implements java.io.Serializable {

	private int area;
	private int tag;

	public AreaTagId() {
	}

	public AreaTagId(int area, int tag) {
		this.area = area;
		this.tag = tag;
	}

	public int getArea() {
		return this.area;
	}

	public void setArea(int area) {
		this.area = area;
	}

	public int getTag() {
		return this.tag;
	}

	public void setTag(int tag) {
		this.tag = tag;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AreaTagId))
			return false;
		AreaTagId castOther = (AreaTagId) other;

		return (this.getArea() == castOther.getArea())
				&& (this.getTag() == castOther.getTag());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getArea();
		result = 37 * result + this.getTag();
		return result;
	}

}
