package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * AreaContainmentId generated by hbm2java
 */
public class AreaContainmentId implements java.io.Serializable {

	private Integer descendant;
	private Integer parent;
	private Integer type;
	private String typeName;
	private Serializable descendantHierarchy;

	public AreaContainmentId() {
	}

	public AreaContainmentId(Integer descendant, Integer parent, Integer type,
			String typeName, Serializable descendantHierarchy) {
		this.descendant = descendant;
		this.parent = parent;
		this.type = type;
		this.typeName = typeName;
		this.descendantHierarchy = descendantHierarchy;
	}

	public Integer getDescendant() {
		return this.descendant;
	}

	public void setDescendant(Integer descendant) {
		this.descendant = descendant;
	}

	public Integer getParent() {
		return this.parent;
	}

	public void setParent(Integer parent) {
		this.parent = parent;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public Serializable getDescendantHierarchy() {
		return this.descendantHierarchy;
	}

	public void setDescendantHierarchy(Serializable descendantHierarchy) {
		this.descendantHierarchy = descendantHierarchy;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AreaContainmentId))
			return false;
		AreaContainmentId castOther = (AreaContainmentId) other;

		return ((this.getDescendant() == castOther.getDescendant()) || (this
				.getDescendant() != null && castOther.getDescendant() != null && this
				.getDescendant().equals(castOther.getDescendant())))
				&& ((this.getParent() == castOther.getParent()) || (this
						.getParent() != null && castOther.getParent() != null && this
						.getParent().equals(castOther.getParent())))
				&& ((this.getType() == castOther.getType()) || (this.getType() != null
						&& castOther.getType() != null && this.getType()
						.equals(castOther.getType())))
				&& ((this.getTypeName() == castOther.getTypeName()) || (this
						.getTypeName() != null
						&& castOther.getTypeName() != null && this
						.getTypeName().equals(castOther.getTypeName())))
				&& ((this.getDescendantHierarchy() == castOther
						.getDescendantHierarchy()) || (this
						.getDescendantHierarchy() != null
						&& castOther.getDescendantHierarchy() != null && this
						.getDescendantHierarchy().equals(
								castOther.getDescendantHierarchy())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getDescendant() == null ? 0 : this.getDescendant()
						.hashCode());
		result = 37 * result
				+ (getParent() == null ? 0 : this.getParent().hashCode());
		result = 37 * result
				+ (getType() == null ? 0 : this.getType().hashCode());
		result = 37 * result
				+ (getTypeName() == null ? 0 : this.getTypeName().hashCode());
		result = 37
				* result
				+ (getDescendantHierarchy() == null ? 0 : this
						.getDescendantHierarchy().hashCode());
		return result;
	}

}
