package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * AreaTagRawId generated by hbm2java
 */
public class AreaTagRawId implements java.io.Serializable {

	private int area;
	private int editor;
	private int tag;

	public AreaTagRawId() {
	}

	public AreaTagRawId(int area, int editor, int tag) {
		this.area = area;
		this.editor = editor;
		this.tag = tag;
	}

	public int getArea() {
		return this.area;
	}

	public void setArea(int area) {
		this.area = area;
	}

	public int getEditor() {
		return this.editor;
	}

	public void setEditor(int editor) {
		this.editor = editor;
	}

	public int getTag() {
		return this.tag;
	}

	public void setTag(int tag) {
		this.tag = tag;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AreaTagRawId))
			return false;
		AreaTagRawId castOther = (AreaTagRawId) other;

		return (this.getArea() == castOther.getArea())
				&& (this.getEditor() == castOther.getEditor())
				&& (this.getTag() == castOther.getTag());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getArea();
		result = 37 * result + this.getEditor();
		result = 37 * result + this.getTag();
		return result;
	}

}
