package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * AreaAnnotation generated by hbm2java
 */
public class AreaAnnotation implements java.io.Serializable {

	private AreaAnnotationId id;

	public AreaAnnotation() {
	}

	public AreaAnnotation(AreaAnnotationId id) {
		this.id = id;
	}

	public AreaAnnotationId getId() {
		return this.id;
	}

	public void setId(AreaAnnotationId id) {
		this.id = id;
	}

}
