package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * AreaTagRaw generated by hbm2java
 */
public class AreaTagRaw implements java.io.Serializable {

	private AreaTagRawId id;
	private boolean isUpvote;

	public AreaTagRaw() {
	}

	public AreaTagRaw(AreaTagRawId id, boolean isUpvote) {
		this.id = id;
		this.isUpvote = isUpvote;
	}

	public AreaTagRawId getId() {
		return this.id;
	}

	public void setId(AreaTagRawId id) {
		this.id = id;
	}

	public boolean isIsUpvote() {
		return this.isUpvote;
	}

	public void setIsUpvote(boolean isUpvote) {
		this.isUpvote = isUpvote;
	}

}
