package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * AreaContainment generated by hbm2java
 */
public class AreaContainment implements java.io.Serializable {

	private AreaContainmentId id;

	public AreaContainment() {
	}

	public AreaContainment(AreaContainmentId id) {
		this.id = id;
	}

	public AreaContainmentId getId() {
		return this.id;
	}

	public void setId(AreaContainmentId id) {
		this.id = id;
	}

}
