package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * AreaAnnotationId generated by hbm2java
 */
public class AreaAnnotationId implements java.io.Serializable {

	private int area;
	private int annotation;

	public AreaAnnotationId() {
	}

	public AreaAnnotationId(int area, int annotation) {
		this.area = area;
		this.annotation = annotation;
	}

	public int getArea() {
		return this.area;
	}

	public void setArea(int area) {
		this.area = area;
	}

	public int getAnnotation() {
		return this.annotation;
	}

	public void setAnnotation(int annotation) {
		this.annotation = annotation;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AreaAnnotationId))
			return false;
		AreaAnnotationId castOther = (AreaAnnotationId) other;

		return (this.getArea() == castOther.getArea())
				&& (this.getAnnotation() == castOther.getAnnotation());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getArea();
		result = 37 * result + this.getAnnotation();
		return result;
	}

}
