package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * Artist generated by hbm2java
 */
public class Artist implements java.io.Serializable {

	private int id;
	private Serializable gid;
	private String name;
	private String sortName;
	private Short beginDateYear;
	private Short beginDateMonth;
	private Short beginDateDay;
	private Short endDateYear;
	private Short endDateMonth;
	private Short endDateDay;
	private Integer type;
	private Integer area;
	private Integer gender;
	private String comment;
	private int editsPending;
	private Date lastUpdated;
	private boolean ended;
	private Integer beginArea;
	private Integer endArea;

	public Artist() {
	}

	public Artist(int id, Serializable gid, String name, String sortName,
			String comment, int editsPending, boolean ended) {
		this.id = id;
		this.gid = gid;
		this.name = name;
		this.sortName = sortName;
		this.comment = comment;
		this.editsPending = editsPending;
		this.ended = ended;
	}

	public Artist(int id, Serializable gid, String name, String sortName,
			Short beginDateYear, Short beginDateMonth, Short beginDateDay,
			Short endDateYear, Short endDateMonth, Short endDateDay,
			Integer type, Integer area, Integer gender, String comment,
			int editsPending, Date lastUpdated, boolean ended,
			Integer beginArea, Integer endArea) {
		this.id = id;
		this.gid = gid;
		this.name = name;
		this.sortName = sortName;
		this.beginDateYear = beginDateYear;
		this.beginDateMonth = beginDateMonth;
		this.beginDateDay = beginDateDay;
		this.endDateYear = endDateYear;
		this.endDateMonth = endDateMonth;
		this.endDateDay = endDateDay;
		this.type = type;
		this.area = area;
		this.gender = gender;
		this.comment = comment;
		this.editsPending = editsPending;
		this.lastUpdated = lastUpdated;
		this.ended = ended;
		this.beginArea = beginArea;
		this.endArea = endArea;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Serializable getGid() {
		return this.gid;
	}

	public void setGid(Serializable gid) {
		this.gid = gid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSortName() {
		return this.sortName;
	}

	public void setSortName(String sortName) {
		this.sortName = sortName;
	}

	public Short getBeginDateYear() {
		return this.beginDateYear;
	}

	public void setBeginDateYear(Short beginDateYear) {
		this.beginDateYear = beginDateYear;
	}

	public Short getBeginDateMonth() {
		return this.beginDateMonth;
	}

	public void setBeginDateMonth(Short beginDateMonth) {
		this.beginDateMonth = beginDateMonth;
	}

	public Short getBeginDateDay() {
		return this.beginDateDay;
	}

	public void setBeginDateDay(Short beginDateDay) {
		this.beginDateDay = beginDateDay;
	}

	public Short getEndDateYear() {
		return this.endDateYear;
	}

	public void setEndDateYear(Short endDateYear) {
		this.endDateYear = endDateYear;
	}

	public Short getEndDateMonth() {
		return this.endDateMonth;
	}

	public void setEndDateMonth(Short endDateMonth) {
		this.endDateMonth = endDateMonth;
	}

	public Short getEndDateDay() {
		return this.endDateDay;
	}

	public void setEndDateDay(Short endDateDay) {
		this.endDateDay = endDateDay;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Integer getArea() {
		return this.area;
	}

	public void setArea(Integer area) {
		this.area = area;
	}

	public Integer getGender() {
		return this.gender;
	}

	public void setGender(Integer gender) {
		this.gender = gender;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public int getEditsPending() {
		return this.editsPending;
	}

	public void setEditsPending(int editsPending) {
		this.editsPending = editsPending;
	}

	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	public boolean isEnded() {
		return this.ended;
	}

	public void setEnded(boolean ended) {
		this.ended = ended;
	}

	public Integer getBeginArea() {
		return this.beginArea;
	}

	public void setBeginArea(Integer beginArea) {
		this.beginArea = beginArea;
	}

	public Integer getEndArea() {
		return this.endArea;
	}

	public void setEndArea(Integer endArea) {
		this.endArea = endArea;
	}

}
