package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * ArtistCreditName generated by hbm2java
 */
public class ArtistCreditName implements java.io.Serializable {

	private ArtistCreditNameId id;
	private int artist;
	private String name;
	private String joinPhrase;

	public ArtistCreditName() {
	}

	public ArtistCreditName(ArtistCreditNameId id, int artist, String name,
			String joinPhrase) {
		this.id = id;
		this.artist = artist;
		this.name = name;
		this.joinPhrase = joinPhrase;
	}

	public ArtistCreditNameId getId() {
		return this.id;
	}

	public void setId(ArtistCreditNameId id) {
		this.id = id;
	}

	public int getArtist() {
		return this.artist;
	}

	public void setArtist(int artist) {
		this.artist = artist;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getJoinPhrase() {
		return this.joinPhrase;
	}

	public void setJoinPhrase(String joinPhrase) {
		this.joinPhrase = joinPhrase;
	}

}
