package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ArtistCredit generated by hbm2java
 */
public class ArtistCredit implements java.io.Serializable {

	private int id;
	private String name;
	private short artistCount;
	private Integer refCount;
	private Date created;

	public ArtistCredit() {
	}

	public ArtistCredit(int id, String name, short artistCount) {
		this.id = id;
		this.name = name;
		this.artistCount = artistCount;
	}

	public ArtistCredit(int id, String name, short artistCount,
			Integer refCount, Date created) {
		this.id = id;
		this.name = name;
		this.artistCount = artistCount;
		this.refCount = refCount;
		this.created = created;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public short getArtistCount() {
		return this.artistCount;
	}

	public void setArtistCount(short artistCount) {
		this.artistCount = artistCount;
	}

	public Integer getRefCount() {
		return this.refCount;
	}

	public void setRefCount(Integer refCount) {
		this.refCount = refCount;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

}
