package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * ArtistRatingRawId generated by hbm2java
 */
public class ArtistRatingRawId implements java.io.Serializable {

	private int artist;
	private int editor;

	public ArtistRatingRawId() {
	}

	public ArtistRatingRawId(int artist, int editor) {
		this.artist = artist;
		this.editor = editor;
	}

	public int getArtist() {
		return this.artist;
	}

	public void setArtist(int artist) {
		this.artist = artist;
	}

	public int getEditor() {
		return this.editor;
	}

	public void setEditor(int editor) {
		this.editor = editor;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArtistRatingRawId))
			return false;
		ArtistRatingRawId castOther = (ArtistRatingRawId) other;

		return (this.getArtist() == castOther.getArtist())
				&& (this.getEditor() == castOther.getEditor());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getArtist();
		result = 37 * result + this.getEditor();
		return result;
	}

}
