package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * ArtistTagRaw generated by hbm2java
 */
public class ArtistTagRaw implements java.io.Serializable {

	private ArtistTagRawId id;
	private boolean isUpvote;

	public ArtistTagRaw() {
	}

	public ArtistTagRaw(ArtistTagRawId id, boolean isUpvote) {
		this.id = id;
		this.isUpvote = isUpvote;
	}

	public ArtistTagRawId getId() {
		return this.id;
	}

	public void setId(ArtistTagRawId id) {
		this.id = id;
	}

	public boolean isIsUpvote() {
		return this.isUpvote;
	}

	public void setIsUpvote(boolean isUpvote) {
		this.isUpvote = isUpvote;
	}

}
