package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * ArtistIsniId generated by hbm2java
 */
public class ArtistIsniId implements java.io.Serializable {

	private int artist;
	private String isni;

	public ArtistIsniId() {
	}

	public ArtistIsniId(int artist, String isni) {
		this.artist = artist;
		this.isni = isni;
	}

	public int getArtist() {
		return this.artist;
	}

	public void setArtist(int artist) {
		this.artist = artist;
	}

	public String getIsni() {
		return this.isni;
	}

	public void setIsni(String isni) {
		this.isni = isni;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArtistIsniId))
			return false;
		ArtistIsniId castOther = (ArtistIsniId) other;

		return (this.getArtist() == castOther.getArtist())
				&& ((this.getIsni() == castOther.getIsni()) || (this.getIsni() != null
						&& castOther.getIsni() != null && this.getIsni()
						.equals(castOther.getIsni())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getArtist();
		result = 37 * result
				+ (getIsni() == null ? 0 : this.getIsni().hashCode());
		return result;
	}

}
