package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * ArtistIpiId generated by hbm2java
 */
public class ArtistIpiId implements java.io.Serializable {

	private int artist;
	private String ipi;

	public ArtistIpiId() {
	}

	public ArtistIpiId(int artist, String ipi) {
		this.artist = artist;
		this.ipi = ipi;
	}

	public int getArtist() {
		return this.artist;
	}

	public void setArtist(int artist) {
		this.artist = artist;
	}

	public String getIpi() {
		return this.ipi;
	}

	public void setIpi(String ipi) {
		this.ipi = ipi;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArtistIpiId))
			return false;
		ArtistIpiId castOther = (ArtistIpiId) other;

		return (this.getArtist() == castOther.getArtist())
				&& ((this.getIpi() == castOther.getIpi()) || (this.getIpi() != null
						&& castOther.getIpi() != null && this.getIpi().equals(
						castOther.getIpi())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getArtist();
		result = 37 * result
				+ (getIpi() == null ? 0 : this.getIpi().hashCode());
		return result;
	}

}
