package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * ArtistTagId generated by hbm2java
 */
public class ArtistTagId implements java.io.Serializable {

	private int artist;
	private int tag;

	public ArtistTagId() {
	}

	public ArtistTagId(int artist, int tag) {
		this.artist = artist;
		this.tag = tag;
	}

	public int getArtist() {
		return this.artist;
	}

	public void setArtist(int artist) {
		this.artist = artist;
	}

	public int getTag() {
		return this.tag;
	}

	public void setTag(int tag) {
		this.tag = tag;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArtistTagId))
			return false;
		ArtistTagId castOther = (ArtistTagId) other;

		return (this.getArtist() == castOther.getArtist())
				&& (this.getTag() == castOther.getTag());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getArtist();
		result = 37 * result + this.getTag();
		return result;
	}

}
