package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ArtistIpi generated by hbm2java
 */
public class ArtistIpi implements java.io.Serializable {

	private ArtistIpiId id;
	private int editsPending;
	private Date created;

	public ArtistIpi() {
	}

	public ArtistIpi(ArtistIpiId id, int editsPending) {
		this.id = id;
		this.editsPending = editsPending;
	}

	public ArtistIpi(ArtistIpiId id, int editsPending, Date created) {
		this.id = id;
		this.editsPending = editsPending;
		this.created = created;
	}

	public ArtistIpiId getId() {
		return this.id;
	}

	public void setId(ArtistIpiId id) {
		this.id = id;
	}

	public int getEditsPending() {
		return this.editsPending;
	}

	public void setEditsPending(int editsPending) {
		this.editsPending = editsPending;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

}
