package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * ArtistCreditNameId generated by hbm2java
 */
public class ArtistCreditNameId implements java.io.Serializable {

	private int artistCredit;
	private short position;

	public ArtistCreditNameId() {
	}

	public ArtistCreditNameId(int artistCredit, short position) {
		this.artistCredit = artistCredit;
		this.position = position;
	}

	public int getArtistCredit() {
		return this.artistCredit;
	}

	public void setArtistCredit(int artistCredit) {
		this.artistCredit = artistCredit;
	}

	public short getPosition() {
		return this.position;
	}

	public void setPosition(short position) {
		this.position = position;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArtistCreditNameId))
			return false;
		ArtistCreditNameId castOther = (ArtistCreditNameId) other;

		return (this.getArtistCredit() == castOther.getArtistCredit())
				&& (this.getPosition() == castOther.getPosition());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getArtistCredit();
		result = 37 * result + this.getPosition();
		return result;
	}

}
