package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * ArtistAnnotation generated by hbm2java
 */
public class ArtistAnnotation implements java.io.Serializable {

	private ArtistAnnotationId id;

	public ArtistAnnotation() {
	}

	public ArtistAnnotation(ArtistAnnotationId id) {
		this.id = id;
	}

	public ArtistAnnotationId getId() {
		return this.id;
	}

	public void setId(ArtistAnnotationId id) {
		this.id = id;
	}

}
