package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * Cdtoc generated by hbm2java
 */
public class Cdtoc implements java.io.Serializable {

	private int id;
	private String discid;
	private String freedbId;
	private int trackCount;
	private int leadoutOffset;
	private Serializable trackOffset;
	private boolean degraded;
	private Date created;

	public Cdtoc() {
	}

	public Cdtoc(int id, String discid, String freedbId, int trackCount,
			int leadoutOffset, Serializable trackOffset, boolean degraded) {
		this.id = id;
		this.discid = discid;
		this.freedbId = freedbId;
		this.trackCount = trackCount;
		this.leadoutOffset = leadoutOffset;
		this.trackOffset = trackOffset;
		this.degraded = degraded;
	}

	public Cdtoc(int id, String discid, String freedbId, int trackCount,
			int leadoutOffset, Serializable trackOffset, boolean degraded,
			Date created) {
		this.id = id;
		this.discid = discid;
		this.freedbId = freedbId;
		this.trackCount = trackCount;
		this.leadoutOffset = leadoutOffset;
		this.trackOffset = trackOffset;
		this.degraded = degraded;
		this.created = created;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDiscid() {
		return this.discid;
	}

	public void setDiscid(String discid) {
		this.discid = discid;
	}

	public String getFreedbId() {
		return this.freedbId;
	}

	public void setFreedbId(String freedbId) {
		this.freedbId = freedbId;
	}

	public int getTrackCount() {
		return this.trackCount;
	}

	public void setTrackCount(int trackCount) {
		this.trackCount = trackCount;
	}

	public int getLeadoutOffset() {
		return this.leadoutOffset;
	}

	public void setLeadoutOffset(int leadoutOffset) {
		this.leadoutOffset = leadoutOffset;
	}

	public Serializable getTrackOffset() {
		return this.trackOffset;
	}

	public void setTrackOffset(Serializable trackOffset) {
		this.trackOffset = trackOffset;
	}

	public boolean isDegraded() {
		return this.degraded;
	}

	public void setDegraded(boolean degraded) {
		this.degraded = degraded;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

}
