package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * CdtocRaw generated by hbm2java
 */
public class CdtocRaw implements java.io.Serializable {

	private int id;
	private int release;
	private String discid;
	private int trackCount;
	private int leadoutOffset;
	private Serializable trackOffset;

	public CdtocRaw() {
	}

	public CdtocRaw(int id, int release, String discid, int trackCount,
			int leadoutOffset, Serializable trackOffset) {
		this.id = id;
		this.release = release;
		this.discid = discid;
		this.trackCount = trackCount;
		this.leadoutOffset = leadoutOffset;
		this.trackOffset = trackOffset;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getRelease() {
		return this.release;
	}

	public void setRelease(int release) {
		this.release = release;
	}

	public String getDiscid() {
		return this.discid;
	}

	public void setDiscid(String discid) {
		this.discid = discid;
	}

	public int getTrackCount() {
		return this.trackCount;
	}

	public void setTrackCount(int trackCount) {
		this.trackCount = trackCount;
	}

	public int getLeadoutOffset() {
		return this.leadoutOffset;
	}

	public void setLeadoutOffset(int leadoutOffset) {
		this.leadoutOffset = leadoutOffset;
	}

	public Serializable getTrackOffset() {
		return this.trackOffset;
	}

	public void setTrackOffset(Serializable trackOffset) {
		this.trackOffset = trackOffset;
	}

}
