package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * CountryArea generated by hbm2java
 */
public class CountryArea implements java.io.Serializable {

	private int area;

	public CountryArea() {
	}

	public CountryArea(int area) {
		this.area = area;
	}

	public int getArea() {
		return this.area;
	}

	public void setArea(int area) {
		this.area = area;
	}

}
