package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * DbmirrorPendingdata generated by hbm2java
 */
public class DbmirrorPendingdata implements java.io.Serializable {

	private DbmirrorPendingdataId id;
	private DbmirrorPending dbmirrorPending;
	private String data;

	public DbmirrorPendingdata() {
	}

	public DbmirrorPendingdata(DbmirrorPendingdataId id,
			DbmirrorPending dbmirrorPending) {
		this.id = id;
		this.dbmirrorPending = dbmirrorPending;
	}

	public DbmirrorPendingdata(DbmirrorPendingdataId id,
			DbmirrorPending dbmirrorPending, String data) {
		this.id = id;
		this.dbmirrorPending = dbmirrorPending;
		this.data = data;
	}

	public DbmirrorPendingdataId getId() {
		return this.id;
	}

	public void setId(DbmirrorPendingdataId id) {
		this.id = id;
	}

	public DbmirrorPending getDbmirrorPending() {
		return this.dbmirrorPending;
	}

	public void setDbmirrorPending(DbmirrorPending dbmirrorPending) {
		this.dbmirrorPending = dbmirrorPending;
	}

	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

}
