package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * DbmirrorPending generated by hbm2java
 */
public class DbmirrorPending implements java.io.Serializable {

	private int seqid;
	private String tablename;
	private Character op;
	private int xid;
	private Set dbmirrorPendingdatas = new HashSet(0);

	public DbmirrorPending() {
	}

	public DbmirrorPending(int seqid, String tablename, int xid) {
		this.seqid = seqid;
		this.tablename = tablename;
		this.xid = xid;
	}

	public DbmirrorPending(int seqid, String tablename, Character op, int xid,
			Set dbmirrorPendingdatas) {
		this.seqid = seqid;
		this.tablename = tablename;
		this.op = op;
		this.xid = xid;
		this.dbmirrorPendingdatas = dbmirrorPendingdatas;
	}

	public int getSeqid() {
		return this.seqid;
	}

	public void setSeqid(int seqid) {
		this.seqid = seqid;
	}

	public String getTablename() {
		return this.tablename;
	}

	public void setTablename(String tablename) {
		this.tablename = tablename;
	}

	public Character getOp() {
		return this.op;
	}

	public void setOp(Character op) {
		this.op = op;
	}

	public int getXid() {
		return this.xid;
	}

	public void setXid(int xid) {
		this.xid = xid;
	}

	public Set getDbmirrorPendingdatas() {
		return this.dbmirrorPendingdatas;
	}

	public void setDbmirrorPendingdatas(Set dbmirrorPendingdatas) {
		this.dbmirrorPendingdatas = dbmirrorPendingdatas;
	}

}
