package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * DbmirrorPendingdataId generated by hbm2java
 */
public class DbmirrorPendingdataId implements java.io.Serializable {

	private int seqid;
	private boolean iskey;

	public DbmirrorPendingdataId() {
	}

	public DbmirrorPendingdataId(int seqid, boolean iskey) {
		this.seqid = seqid;
		this.iskey = iskey;
	}

	public int getSeqid() {
		return this.seqid;
	}

	public void setSeqid(int seqid) {
		this.seqid = seqid;
	}

	public boolean isIskey() {
		return this.iskey;
	}

	public void setIskey(boolean iskey) {
		this.iskey = iskey;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DbmirrorPendingdataId))
			return false;
		DbmirrorPendingdataId castOther = (DbmirrorPendingdataId) other;

		return (this.getSeqid() == castOther.getSeqid())
				&& (this.isIskey() == castOther.isIskey());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSeqid();
		result = 37 * result + (this.isIskey() ? 1 : 0);
		return result;
	}

}
