package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditorCollectionRecording generated by hbm2java
 */
public class EditorCollectionRecording implements java.io.Serializable {

	private EditorCollectionRecordingId id;

	public EditorCollectionRecording() {
	}

	public EditorCollectionRecording(EditorCollectionRecordingId id) {
		this.id = id;
	}

	public EditorCollectionRecordingId getId() {
		return this.id;
	}

	public void setId(EditorCollectionRecordingId id) {
		this.id = id;
	}

}
