package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditorCollectionPlace generated by hbm2java
 */
public class EditorCollectionPlace implements java.io.Serializable {

	private EditorCollectionPlaceId id;

	public EditorCollectionPlace() {
	}

	public EditorCollectionPlace(EditorCollectionPlaceId id) {
		this.id = id;
	}

	public EditorCollectionPlaceId getId() {
		return this.id;
	}

	public void setId(EditorCollectionPlaceId id) {
		this.id = id;
	}

}
