package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditLabel generated by hbm2java
 */
public class EditLabel implements java.io.Serializable {

	private EditLabelId id;
	private short status;

	public EditLabel() {
	}

	public EditLabel(EditLabelId id, short status) {
		this.id = id;
		this.status = status;
	}

	public EditLabelId getId() {
		return this.id;
	}

	public void setId(EditLabelId id) {
		this.id = id;
	}

	public short getStatus() {
		return this.status;
	}

	public void setStatus(short status) {
		this.status = status;
	}

}
