package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditorCollectionEvent generated by hbm2java
 */
public class EditorCollectionEvent implements java.io.Serializable {

	private EditorCollectionEventId id;

	public EditorCollectionEvent() {
	}

	public EditorCollectionEvent(EditorCollectionEventId id) {
		this.id = id;
	}

	public EditorCollectionEventId getId() {
		return this.id;
	}

	public void setId(EditorCollectionEventId id) {
		this.id = id;
	}

}
