package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditRecording generated by hbm2java
 */
public class EditRecording implements java.io.Serializable {

	private EditRecordingId id;

	public EditRecording() {
	}

	public EditRecording(EditRecordingId id) {
		this.id = id;
	}

	public EditRecordingId getId() {
		return this.id;
	}

	public void setId(EditRecordingId id) {
		this.id = id;
	}

}
