package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditorCollectionLabel generated by hbm2java
 */
public class EditorCollectionLabel implements java.io.Serializable {

	private EditorCollectionLabelId id;

	public EditorCollectionLabel() {
	}

	public EditorCollectionLabel(EditorCollectionLabelId id) {
		this.id = id;
	}

	public EditorCollectionLabelId getId() {
		return this.id;
	}

	public void setId(EditorCollectionLabelId id) {
		this.id = id;
	}

}
