package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditEvent generated by hbm2java
 */
public class EditEvent implements java.io.Serializable {

	private EditEventId id;

	public EditEvent() {
	}

	public EditEvent(EditEventId id) {
		this.id = id;
	}

	public EditEventId getId() {
		return this.id;
	}

	public void setId(EditEventId id) {
		this.id = id;
	}

}
