package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditorCollectionAreaId generated by hbm2java
 */
public class EditorCollectionAreaId implements java.io.Serializable {

	private int collection;
	private int area;

	public EditorCollectionAreaId() {
	}

	public EditorCollectionAreaId(int collection, int area) {
		this.collection = collection;
		this.area = area;
	}

	public int getCollection() {
		return this.collection;
	}

	public void setCollection(int collection) {
		this.collection = collection;
	}

	public int getArea() {
		return this.area;
	}

	public void setArea(int area) {
		this.area = area;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EditorCollectionAreaId))
			return false;
		EditorCollectionAreaId castOther = (EditorCollectionAreaId) other;

		return (this.getCollection() == castOther.getCollection())
				&& (this.getArea() == castOther.getArea());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCollection();
		result = 37 * result + this.getArea();
		return result;
	}

}
