package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * EditorOauthToken generated by hbm2java
 */
public class EditorOauthToken implements java.io.Serializable {

	private int id;
	private int editor;
	private int application;
	private String authorizationCode;
	private String refreshToken;
	private String accessToken;
	private Date expireTime;
	private int scope;
	private Date granted;

	public EditorOauthToken() {
	}

	public EditorOauthToken(int id, int editor, int application,
			Date expireTime, int scope, Date granted) {
		this.id = id;
		this.editor = editor;
		this.application = application;
		this.expireTime = expireTime;
		this.scope = scope;
		this.granted = granted;
	}

	public EditorOauthToken(int id, int editor, int application,
			String authorizationCode, String refreshToken, String accessToken,
			Date expireTime, int scope, Date granted) {
		this.id = id;
		this.editor = editor;
		this.application = application;
		this.authorizationCode = authorizationCode;
		this.refreshToken = refreshToken;
		this.accessToken = accessToken;
		this.expireTime = expireTime;
		this.scope = scope;
		this.granted = granted;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getEditor() {
		return this.editor;
	}

	public void setEditor(int editor) {
		this.editor = editor;
	}

	public int getApplication() {
		return this.application;
	}

	public void setApplication(int application) {
		this.application = application;
	}

	public String getAuthorizationCode() {
		return this.authorizationCode;
	}

	public void setAuthorizationCode(String authorizationCode) {
		this.authorizationCode = authorizationCode;
	}

	public String getRefreshToken() {
		return this.refreshToken;
	}

	public void setRefreshToken(String refreshToken) {
		this.refreshToken = refreshToken;
	}

	public String getAccessToken() {
		return this.accessToken;
	}

	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken;
	}

	public Date getExpireTime() {
		return this.expireTime;
	}

	public void setExpireTime(Date expireTime) {
		this.expireTime = expireTime;
	}

	public int getScope() {
		return this.scope;
	}

	public void setScope(int scope) {
		this.scope = scope;
	}

	public Date getGranted() {
		return this.granted;
	}

	public void setGranted(Date granted) {
		this.granted = granted;
	}

}
