package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditorCollectionPlaceId generated by hbm2java
 */
public class EditorCollectionPlaceId implements java.io.Serializable {

	private int collection;
	private int place;

	public EditorCollectionPlaceId() {
	}

	public EditorCollectionPlaceId(int collection, int place) {
		this.collection = collection;
		this.place = place;
	}

	public int getCollection() {
		return this.collection;
	}

	public void setCollection(int collection) {
		this.collection = collection;
	}

	public int getPlace() {
		return this.place;
	}

	public void setPlace(int place) {
		this.place = place;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EditorCollectionPlaceId))
			return false;
		EditorCollectionPlaceId castOther = (EditorCollectionPlaceId) other;

		return (this.getCollection() == castOther.getCollection())
				&& (this.getPlace() == castOther.getPlace());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCollection();
		result = 37 * result + this.getPlace();
		return result;
	}

}
