package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditRecordingId generated by hbm2java
 */
public class EditRecordingId implements java.io.Serializable {

	private int edit;
	private int recording;

	public EditRecordingId() {
	}

	public EditRecordingId(int edit, int recording) {
		this.edit = edit;
		this.recording = recording;
	}

	public int getEdit() {
		return this.edit;
	}

	public void setEdit(int edit) {
		this.edit = edit;
	}

	public int getRecording() {
		return this.recording;
	}

	public void setRecording(int recording) {
		this.recording = recording;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EditRecordingId))
			return false;
		EditRecordingId castOther = (EditRecordingId) other;

		return (this.getEdit() == castOther.getEdit())
				&& (this.getRecording() == castOther.getRecording());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEdit();
		result = 37 * result + this.getRecording();
		return result;
	}

}
