package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * EditorSubscribeSeriesDeletedId generated by hbm2java
 */
public class EditorSubscribeSeriesDeletedId implements java.io.Serializable {

	private int editor;
	private Serializable gid;

	public EditorSubscribeSeriesDeletedId() {
	}

	public EditorSubscribeSeriesDeletedId(int editor, Serializable gid) {
		this.editor = editor;
		this.gid = gid;
	}

	public int getEditor() {
		return this.editor;
	}

	public void setEditor(int editor) {
		this.editor = editor;
	}

	public Serializable getGid() {
		return this.gid;
	}

	public void setGid(Serializable gid) {
		this.gid = gid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EditorSubscribeSeriesDeletedId))
			return false;
		EditorSubscribeSeriesDeletedId castOther = (EditorSubscribeSeriesDeletedId) other;

		return (this.getEditor() == castOther.getEditor())
				&& ((this.getGid() == castOther.getGid()) || (this.getGid() != null
						&& castOther.getGid() != null && this.getGid().equals(
						castOther.getGid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEditor();
		result = 37 * result
				+ (getGid() == null ? 0 : this.getGid().hashCode());
		return result;
	}

}
