package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditorCollectionSeriesId generated by hbm2java
 */
public class EditorCollectionSeriesId implements java.io.Serializable {

	private int collection;
	private int series;

	public EditorCollectionSeriesId() {
	}

	public EditorCollectionSeriesId(int collection, int series) {
		this.collection = collection;
		this.series = series;
	}

	public int getCollection() {
		return this.collection;
	}

	public void setCollection(int collection) {
		this.collection = collection;
	}

	public int getSeries() {
		return this.series;
	}

	public void setSeries(int series) {
		this.series = series;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EditorCollectionSeriesId))
			return false;
		EditorCollectionSeriesId castOther = (EditorCollectionSeriesId) other;

		return (this.getCollection() == castOther.getCollection())
				&& (this.getSeries() == castOther.getSeries());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCollection();
		result = 37 * result + this.getSeries();
		return result;
	}

}
