package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditInstrument generated by hbm2java
 */
public class EditInstrument implements java.io.Serializable {

	private EditInstrumentId id;

	public EditInstrument() {
	}

	public EditInstrument(EditInstrumentId id) {
		this.id = id;
	}

	public EditInstrumentId getId() {
		return this.id;
	}

	public void setId(EditInstrumentId id) {
		this.id = id;
	}

}
