package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditAreaId generated by hbm2java
 */
public class EditAreaId implements java.io.Serializable {

	private int edit;
	private int area;

	public EditAreaId() {
	}

	public EditAreaId(int edit, int area) {
		this.edit = edit;
		this.area = area;
	}

	public int getEdit() {
		return this.edit;
	}

	public void setEdit(int edit) {
		this.edit = edit;
	}

	public int getArea() {
		return this.area;
	}

	public void setArea(int area) {
		this.area = area;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EditAreaId))
			return false;
		EditAreaId castOther = (EditAreaId) other;

		return (this.getEdit() == castOther.getEdit())
				&& (this.getArea() == castOther.getArea());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEdit();
		result = 37 * result + this.getArea();
		return result;
	}

}
