package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditorCollectionReleaseId generated by hbm2java
 */
public class EditorCollectionReleaseId implements java.io.Serializable {

	private int collection;
	private int release;

	public EditorCollectionReleaseId() {
	}

	public EditorCollectionReleaseId(int collection, int release) {
		this.collection = collection;
		this.release = release;
	}

	public int getCollection() {
		return this.collection;
	}

	public void setCollection(int collection) {
		this.collection = collection;
	}

	public int getRelease() {
		return this.release;
	}

	public void setRelease(int release) {
		this.release = release;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EditorCollectionReleaseId))
			return false;
		EditorCollectionReleaseId castOther = (EditorCollectionReleaseId) other;

		return (this.getCollection() == castOther.getCollection())
				&& (this.getRelease() == castOther.getRelease());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCollection();
		result = 37 * result + this.getRelease();
		return result;
	}

}
