package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditorCollectionRelease generated by hbm2java
 */
public class EditorCollectionRelease implements java.io.Serializable {

	private EditorCollectionReleaseId id;

	public EditorCollectionRelease() {
	}

	public EditorCollectionRelease(EditorCollectionReleaseId id) {
		this.id = id;
	}

	public EditorCollectionReleaseId getId() {
		return this.id;
	}

	public void setId(EditorCollectionReleaseId id) {
		this.id = id;
	}

}
