package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditEventId generated by hbm2java
 */
public class EditEventId implements java.io.Serializable {

	private int edit;
	private int event;

	public EditEventId() {
	}

	public EditEventId(int edit, int event) {
		this.edit = edit;
		this.event = event;
	}

	public int getEdit() {
		return this.edit;
	}

	public void setEdit(int edit) {
		this.edit = edit;
	}

	public int getEvent() {
		return this.event;
	}

	public void setEvent(int event) {
		this.event = event;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EditEventId))
			return false;
		EditEventId castOther = (EditEventId) other;

		return (this.getEdit() == castOther.getEdit())
				&& (this.getEvent() == castOther.getEvent());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEdit();
		result = 37 * result + this.getEvent();
		return result;
	}

}
