package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Edit generated by hbm2java
 */
public class Edit implements java.io.Serializable {

	private int id;
	private int editor;
	private short type;
	private short status;
	private String data;
	private int yesVotes;
	private int noVotes;
	private short autoedit;
	private Date openTime;
	private Date closeTime;
	private Date expireTime;
	private Integer language;
	private short quality;

	public Edit() {
	}

	public Edit(int id, int editor, short type, short status, String data,
			int yesVotes, int noVotes, short autoedit, Date expireTime,
			short quality) {
		this.id = id;
		this.editor = editor;
		this.type = type;
		this.status = status;
		this.data = data;
		this.yesVotes = yesVotes;
		this.noVotes = noVotes;
		this.autoedit = autoedit;
		this.expireTime = expireTime;
		this.quality = quality;
	}

	public Edit(int id, int editor, short type, short status, String data,
			int yesVotes, int noVotes, short autoedit, Date openTime,
			Date closeTime, Date expireTime, Integer language, short quality) {
		this.id = id;
		this.editor = editor;
		this.type = type;
		this.status = status;
		this.data = data;
		this.yesVotes = yesVotes;
		this.noVotes = noVotes;
		this.autoedit = autoedit;
		this.openTime = openTime;
		this.closeTime = closeTime;
		this.expireTime = expireTime;
		this.language = language;
		this.quality = quality;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getEditor() {
		return this.editor;
	}

	public void setEditor(int editor) {
		this.editor = editor;
	}

	public short getType() {
		return this.type;
	}

	public void setType(short type) {
		this.type = type;
	}

	public short getStatus() {
		return this.status;
	}

	public void setStatus(short status) {
		this.status = status;
	}

	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

	public int getYesVotes() {
		return this.yesVotes;
	}

	public void setYesVotes(int yesVotes) {
		this.yesVotes = yesVotes;
	}

	public int getNoVotes() {
		return this.noVotes;
	}

	public void setNoVotes(int noVotes) {
		this.noVotes = noVotes;
	}

	public short getAutoedit() {
		return this.autoedit;
	}

	public void setAutoedit(short autoedit) {
		this.autoedit = autoedit;
	}

	public Date getOpenTime() {
		return this.openTime;
	}

	public void setOpenTime(Date openTime) {
		this.openTime = openTime;
	}

	public Date getCloseTime() {
		return this.closeTime;
	}

	public void setCloseTime(Date closeTime) {
		this.closeTime = closeTime;
	}

	public Date getExpireTime() {
		return this.expireTime;
	}

	public void setExpireTime(Date expireTime) {
		this.expireTime = expireTime;
	}

	public Integer getLanguage() {
		return this.language;
	}

	public void setLanguage(Integer language) {
		this.language = language;
	}

	public short getQuality() {
		return this.quality;
	}

	public void setQuality(short quality) {
		this.quality = quality;
	}

}
