package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditSeriesId generated by hbm2java
 */
public class EditSeriesId implements java.io.Serializable {

	private int edit;
	private int series;

	public EditSeriesId() {
	}

	public EditSeriesId(int edit, int series) {
		this.edit = edit;
		this.series = series;
	}

	public int getEdit() {
		return this.edit;
	}

	public void setEdit(int edit) {
		this.edit = edit;
	}

	public int getSeries() {
		return this.series;
	}

	public void setSeries(int series) {
		this.series = series;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EditSeriesId))
			return false;
		EditSeriesId castOther = (EditSeriesId) other;

		return (this.getEdit() == castOther.getEdit())
				&& (this.getSeries() == castOther.getSeries());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEdit();
		result = 37 * result + this.getSeries();
		return result;
	}

}
