package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditUrlId generated by hbm2java
 */
public class EditUrlId implements java.io.Serializable {

	private int edit;
	private int url;

	public EditUrlId() {
	}

	public EditUrlId(int edit, int url) {
		this.edit = edit;
		this.url = url;
	}

	public int getEdit() {
		return this.edit;
	}

	public void setEdit(int edit) {
		this.edit = edit;
	}

	public int getUrl() {
		return this.url;
	}

	public void setUrl(int url) {
		this.url = url;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EditUrlId))
			return false;
		EditUrlId castOther = (EditUrlId) other;

		return (this.getEdit() == castOther.getEdit())
				&& (this.getUrl() == castOther.getUrl());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEdit();
		result = 37 * result + this.getUrl();
		return result;
	}

}
