package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditorSubscribeCollection generated by hbm2java
 */
public class EditorSubscribeCollection implements java.io.Serializable {

	private int id;
	private int editor;
	private int collection;
	private int lastEditSent;
	private boolean available;
	private String lastSeenName;

	public EditorSubscribeCollection() {
	}

	public EditorSubscribeCollection(int id, int editor, int collection,
			int lastEditSent, boolean available) {
		this.id = id;
		this.editor = editor;
		this.collection = collection;
		this.lastEditSent = lastEditSent;
		this.available = available;
	}

	public EditorSubscribeCollection(int id, int editor, int collection,
			int lastEditSent, boolean available, String lastSeenName) {
		this.id = id;
		this.editor = editor;
		this.collection = collection;
		this.lastEditSent = lastEditSent;
		this.available = available;
		this.lastSeenName = lastSeenName;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getEditor() {
		return this.editor;
	}

	public void setEditor(int editor) {
		this.editor = editor;
	}

	public int getCollection() {
		return this.collection;
	}

	public void setCollection(int collection) {
		this.collection = collection;
	}

	public int getLastEditSent() {
		return this.lastEditSent;
	}

	public void setLastEditSent(int lastEditSent) {
		this.lastEditSent = lastEditSent;
	}

	public boolean isAvailable() {
		return this.available;
	}

	public void setAvailable(boolean available) {
		this.available = available;
	}

	public String getLastSeenName() {
		return this.lastSeenName;
	}

	public void setLastSeenName(String lastSeenName) {
		this.lastSeenName = lastSeenName;
	}

}
