package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditorCollectionWorkId generated by hbm2java
 */
public class EditorCollectionWorkId implements java.io.Serializable {

	private int collection;
	private int work;

	public EditorCollectionWorkId() {
	}

	public EditorCollectionWorkId(int collection, int work) {
		this.collection = collection;
		this.work = work;
	}

	public int getCollection() {
		return this.collection;
	}

	public void setCollection(int collection) {
		this.collection = collection;
	}

	public int getWork() {
		return this.work;
	}

	public void setWork(int work) {
		this.work = work;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EditorCollectionWorkId))
			return false;
		EditorCollectionWorkId castOther = (EditorCollectionWorkId) other;

		return (this.getCollection() == castOther.getCollection())
				&& (this.getWork() == castOther.getWork());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCollection();
		result = 37 * result + this.getWork();
		return result;
	}

}
