package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditorLanguageId generated by hbm2java
 */
public class EditorLanguageId implements java.io.Serializable {

	private int editor;
	private int language;

	public EditorLanguageId() {
	}

	public EditorLanguageId(int editor, int language) {
		this.editor = editor;
		this.language = language;
	}

	public int getEditor() {
		return this.editor;
	}

	public void setEditor(int editor) {
		this.editor = editor;
	}

	public int getLanguage() {
		return this.language;
	}

	public void setLanguage(int language) {
		this.language = language;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EditorLanguageId))
			return false;
		EditorLanguageId castOther = (EditorLanguageId) other;

		return (this.getEditor() == castOther.getEditor())
				&& (this.getLanguage() == castOther.getLanguage());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEditor();
		result = 37 * result + this.getLanguage();
		return result;
	}

}
