package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditorPreference generated by hbm2java
 */
public class EditorPreference implements java.io.Serializable {

	private int id;
	private int editor;
	private String name;
	private String value;

	public EditorPreference() {
	}

	public EditorPreference(int id, int editor, String name, String value) {
		this.id = id;
		this.editor = editor;
		this.name = name;
		this.value = value;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getEditor() {
		return this.editor;
	}

	public void setEditor(int editor) {
		this.editor = editor;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
