package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditorCollectionReleaseGroup generated by hbm2java
 */
public class EditorCollectionReleaseGroup implements java.io.Serializable {

	private EditorCollectionReleaseGroupId id;

	public EditorCollectionReleaseGroup() {
	}

	public EditorCollectionReleaseGroup(EditorCollectionReleaseGroupId id) {
		this.id = id;
	}

	public EditorCollectionReleaseGroupId getId() {
		return this.id;
	}

	public void setId(EditorCollectionReleaseGroupId id) {
		this.id = id;
	}

}
