package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditorSubscribeLabel generated by hbm2java
 */
public class EditorSubscribeLabel implements java.io.Serializable {

	private int id;
	private int editor;
	private int label;
	private int lastEditSent;

	public EditorSubscribeLabel() {
	}

	public EditorSubscribeLabel(int id, int editor, int label, int lastEditSent) {
		this.id = id;
		this.editor = editor;
		this.label = label;
		this.lastEditSent = lastEditSent;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getEditor() {
		return this.editor;
	}

	public void setEditor(int editor) {
		this.editor = editor;
	}

	public int getLabel() {
		return this.label;
	}

	public void setLabel(int label) {
		this.label = label;
	}

	public int getLastEditSent() {
		return this.lastEditSent;
	}

	public void setLastEditSent(int lastEditSent) {
		this.lastEditSent = lastEditSent;
	}

}
