package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditorWatchReleaseStatusId generated by hbm2java
 */
public class EditorWatchReleaseStatusId implements java.io.Serializable {

	private int editor;
	private int releaseStatus;

	public EditorWatchReleaseStatusId() {
	}

	public EditorWatchReleaseStatusId(int editor, int releaseStatus) {
		this.editor = editor;
		this.releaseStatus = releaseStatus;
	}

	public int getEditor() {
		return this.editor;
	}

	public void setEditor(int editor) {
		this.editor = editor;
	}

	public int getReleaseStatus() {
		return this.releaseStatus;
	}

	public void setReleaseStatus(int releaseStatus) {
		this.releaseStatus = releaseStatus;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EditorWatchReleaseStatusId))
			return false;
		EditorWatchReleaseStatusId castOther = (EditorWatchReleaseStatusId) other;

		return (this.getEditor() == castOther.getEditor())
				&& (this.getReleaseStatus() == castOther.getReleaseStatus());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEditor();
		result = 37 * result + this.getReleaseStatus();
		return result;
	}

}
