package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditPlace generated by hbm2java
 */
public class EditPlace implements java.io.Serializable {

	private EditPlaceId id;

	public EditPlace() {
	}

	public EditPlace(EditPlaceId id) {
		this.id = id;
	}

	public EditPlaceId getId() {
		return this.id;
	}

	public void setId(EditPlaceId id) {
		this.id = id;
	}

}
