package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * EditorLanguage generated by hbm2java
 */
public class EditorLanguage implements java.io.Serializable {

	private EditorLanguageId id;
	private Serializable fluency;

	public EditorLanguage() {
	}

	public EditorLanguage(EditorLanguageId id, Serializable fluency) {
		this.id = id;
		this.fluency = fluency;
	}

	public EditorLanguageId getId() {
		return this.id;
	}

	public void setId(EditorLanguageId id) {
		this.id = id;
	}

	public Serializable getFluency() {
		return this.fluency;
	}

	public void setFluency(Serializable fluency) {
		this.fluency = fluency;
	}

}
