package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditInstrumentId generated by hbm2java
 */
public class EditInstrumentId implements java.io.Serializable {

	private int edit;
	private int instrument;

	public EditInstrumentId() {
	}

	public EditInstrumentId(int edit, int instrument) {
		this.edit = edit;
		this.instrument = instrument;
	}

	public int getEdit() {
		return this.edit;
	}

	public void setEdit(int edit) {
		this.edit = edit;
	}

	public int getInstrument() {
		return this.instrument;
	}

	public void setInstrument(int instrument) {
		this.instrument = instrument;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EditInstrumentId))
			return false;
		EditInstrumentId castOther = (EditInstrumentId) other;

		return (this.getEdit() == castOther.getEdit())
				&& (this.getInstrument() == castOther.getInstrument());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEdit();
		result = 37 * result + this.getInstrument();
		return result;
	}

}
