package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditArtist generated by hbm2java
 */
public class EditArtist implements java.io.Serializable {

	private EditArtistId id;
	private short status;

	public EditArtist() {
	}

	public EditArtist(EditArtistId id, short status) {
		this.id = id;
		this.status = status;
	}

	public EditArtistId getId() {
		return this.id;
	}

	public void setId(EditArtistId id) {
		this.id = id;
	}

	public short getStatus() {
		return this.status;
	}

	public void setStatus(short status) {
		this.status = status;
	}

}
