package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditorWatchReleaseStatus generated by hbm2java
 */
public class EditorWatchReleaseStatus implements java.io.Serializable {

	private EditorWatchReleaseStatusId id;

	public EditorWatchReleaseStatus() {
	}

	public EditorWatchReleaseStatus(EditorWatchReleaseStatusId id) {
		this.id = id;
	}

	public EditorWatchReleaseStatusId getId() {
		return this.id;
	}

	public void setId(EditorWatchReleaseStatusId id) {
		this.id = id;
	}

}
