package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditReleaseGroup generated by hbm2java
 */
public class EditReleaseGroup implements java.io.Serializable {

	private EditReleaseGroupId id;

	public EditReleaseGroup() {
	}

	public EditReleaseGroup(EditReleaseGroupId id) {
		this.id = id;
	}

	public EditReleaseGroupId getId() {
		return this.id;
	}

	public void setId(EditReleaseGroupId id) {
		this.id = id;
	}

}
