package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditorWatchReleaseGroupTypeId generated by hbm2java
 */
public class EditorWatchReleaseGroupTypeId implements java.io.Serializable {

	private int editor;
	private int releaseGroupType;

	public EditorWatchReleaseGroupTypeId() {
	}

	public EditorWatchReleaseGroupTypeId(int editor, int releaseGroupType) {
		this.editor = editor;
		this.releaseGroupType = releaseGroupType;
	}

	public int getEditor() {
		return this.editor;
	}

	public void setEditor(int editor) {
		this.editor = editor;
	}

	public int getReleaseGroupType() {
		return this.releaseGroupType;
	}

	public void setReleaseGroupType(int releaseGroupType) {
		this.releaseGroupType = releaseGroupType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EditorWatchReleaseGroupTypeId))
			return false;
		EditorWatchReleaseGroupTypeId castOther = (EditorWatchReleaseGroupTypeId) other;

		return (this.getEditor() == castOther.getEditor())
				&& (this.getReleaseGroupType() == castOther
						.getReleaseGroupType());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEditor();
		result = 37 * result + this.getReleaseGroupType();
		return result;
	}

}
