package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditorWatchReleaseGroupType generated by hbm2java
 */
public class EditorWatchReleaseGroupType implements java.io.Serializable {

	private EditorWatchReleaseGroupTypeId id;

	public EditorWatchReleaseGroupType() {
	}

	public EditorWatchReleaseGroupType(EditorWatchReleaseGroupTypeId id) {
		this.id = id;
	}

	public EditorWatchReleaseGroupTypeId getId() {
		return this.id;
	}

	public void setId(EditorWatchReleaseGroupTypeId id) {
		this.id = id;
	}

}
