package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Editor generated by hbm2java
 */
public class Editor implements java.io.Serializable {

	private int id;
	private String name;
	private Integer privs;
	private String email;
	private String website;
	private String bio;
	private Date memberSince;
	private Date emailConfirmDate;
	private Date lastLoginDate;
	private Integer editsAccepted;
	private Integer editsRejected;
	private Integer autoEditsAccepted;
	private Integer editsFailed;
	private Date lastUpdated;
	private Date birthDate;
	private Integer gender;
	private Integer area;
	private String password;
	private String ha1;
	private boolean deleted;

	public Editor() {
	}

	public Editor(int id, String name, String password, String ha1,
			boolean deleted) {
		this.id = id;
		this.name = name;
		this.password = password;
		this.ha1 = ha1;
		this.deleted = deleted;
	}

	public Editor(int id, String name, Integer privs, String email,
			String website, String bio, Date memberSince,
			Date emailConfirmDate, Date lastLoginDate, Integer editsAccepted,
			Integer editsRejected, Integer autoEditsAccepted,
			Integer editsFailed, Date lastUpdated, Date birthDate,
			Integer gender, Integer area, String password, String ha1,
			boolean deleted) {
		this.id = id;
		this.name = name;
		this.privs = privs;
		this.email = email;
		this.website = website;
		this.bio = bio;
		this.memberSince = memberSince;
		this.emailConfirmDate = emailConfirmDate;
		this.lastLoginDate = lastLoginDate;
		this.editsAccepted = editsAccepted;
		this.editsRejected = editsRejected;
		this.autoEditsAccepted = autoEditsAccepted;
		this.editsFailed = editsFailed;
		this.lastUpdated = lastUpdated;
		this.birthDate = birthDate;
		this.gender = gender;
		this.area = area;
		this.password = password;
		this.ha1 = ha1;
		this.deleted = deleted;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getPrivs() {
		return this.privs;
	}

	public void setPrivs(Integer privs) {
		this.privs = privs;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public String getBio() {
		return this.bio;
	}

	public void setBio(String bio) {
		this.bio = bio;
	}

	public Date getMemberSince() {
		return this.memberSince;
	}

	public void setMemberSince(Date memberSince) {
		this.memberSince = memberSince;
	}

	public Date getEmailConfirmDate() {
		return this.emailConfirmDate;
	}

	public void setEmailConfirmDate(Date emailConfirmDate) {
		this.emailConfirmDate = emailConfirmDate;
	}

	public Date getLastLoginDate() {
		return this.lastLoginDate;
	}

	public void setLastLoginDate(Date lastLoginDate) {
		this.lastLoginDate = lastLoginDate;
	}

	public Integer getEditsAccepted() {
		return this.editsAccepted;
	}

	public void setEditsAccepted(Integer editsAccepted) {
		this.editsAccepted = editsAccepted;
	}

	public Integer getEditsRejected() {
		return this.editsRejected;
	}

	public void setEditsRejected(Integer editsRejected) {
		this.editsRejected = editsRejected;
	}

	public Integer getAutoEditsAccepted() {
		return this.autoEditsAccepted;
	}

	public void setAutoEditsAccepted(Integer autoEditsAccepted) {
		this.autoEditsAccepted = autoEditsAccepted;
	}

	public Integer getEditsFailed() {
		return this.editsFailed;
	}

	public void setEditsFailed(Integer editsFailed) {
		this.editsFailed = editsFailed;
	}

	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	public Integer getGender() {
		return this.gender;
	}

	public void setGender(Integer gender) {
		this.gender = gender;
	}

	public Integer getArea() {
		return this.area;
	}

	public void setArea(Integer area) {
		this.area = area;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getHa1() {
		return this.ha1;
	}

	public void setHa1(String ha1) {
		this.ha1 = ha1;
	}

	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

}
