package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditorSubscribeSeriesDeleted generated by hbm2java
 */
public class EditorSubscribeSeriesDeleted implements java.io.Serializable {

	private EditorSubscribeSeriesDeletedId id;
	private int deletedBy;

	public EditorSubscribeSeriesDeleted() {
	}

	public EditorSubscribeSeriesDeleted(EditorSubscribeSeriesDeletedId id,
			int deletedBy) {
		this.id = id;
		this.deletedBy = deletedBy;
	}

	public EditorSubscribeSeriesDeletedId getId() {
		return this.id;
	}

	public void setId(EditorSubscribeSeriesDeletedId id) {
		this.id = id;
	}

	public int getDeletedBy() {
		return this.deletedBy;
	}

	public void setDeletedBy(int deletedBy) {
		this.deletedBy = deletedBy;
	}

}
