package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditorSubscribeSeries generated by hbm2java
 */
public class EditorSubscribeSeries implements java.io.Serializable {

	private int id;
	private int editor;
	private int series;
	private int lastEditSent;

	public EditorSubscribeSeries() {
	}

	public EditorSubscribeSeries(int id, int editor, int series,
			int lastEditSent) {
		this.id = id;
		this.editor = editor;
		this.series = series;
		this.lastEditSent = lastEditSent;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getEditor() {
		return this.editor;
	}

	public void setEditor(int editor) {
		this.editor = editor;
	}

	public int getSeries() {
		return this.series;
	}

	public void setSeries(int series) {
		this.series = series;
	}

	public int getLastEditSent() {
		return this.lastEditSent;
	}

	public void setLastEditSent(int lastEditSent) {
		this.lastEditSent = lastEditSent;
	}

}
