package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * EditorCollection generated by hbm2java
 */
public class EditorCollection implements java.io.Serializable {

	private int id;
	private Serializable gid;
	private int editor;
	private String name;
	private boolean public_;
	private String description;
	private int type;

	public EditorCollection() {
	}

	public EditorCollection(int id, Serializable gid, int editor, String name,
			boolean public_, String description, int type) {
		this.id = id;
		this.gid = gid;
		this.editor = editor;
		this.name = name;
		this.public_ = public_;
		this.description = description;
		this.type = type;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Serializable getGid() {
		return this.gid;
	}

	public void setGid(Serializable gid) {
		this.gid = gid;
	}

	public int getEditor() {
		return this.editor;
	}

	public void setEditor(int editor) {
		this.editor = editor;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean isPublic_() {
		return this.public_;
	}

	public void setPublic_(boolean public_) {
		this.public_ = public_;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

}
