package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditorCollectionInstrumentId generated by hbm2java
 */
public class EditorCollectionInstrumentId implements java.io.Serializable {

	private int collection;
	private int instrument;

	public EditorCollectionInstrumentId() {
	}

	public EditorCollectionInstrumentId(int collection, int instrument) {
		this.collection = collection;
		this.instrument = instrument;
	}

	public int getCollection() {
		return this.collection;
	}

	public void setCollection(int collection) {
		this.collection = collection;
	}

	public int getInstrument() {
		return this.instrument;
	}

	public void setInstrument(int instrument) {
		this.instrument = instrument;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EditorCollectionInstrumentId))
			return false;
		EditorCollectionInstrumentId castOther = (EditorCollectionInstrumentId) other;

		return (this.getCollection() == castOther.getCollection())
				&& (this.getInstrument() == castOther.getInstrument());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCollection();
		result = 37 * result + this.getInstrument();
		return result;
	}

}
