package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditSeries generated by hbm2java
 */
public class EditSeries implements java.io.Serializable {

	private EditSeriesId id;

	public EditSeries() {
	}

	public EditSeries(EditSeriesId id) {
		this.id = id;
	}

	public EditSeriesId getId() {
		return this.id;
	}

	public void setId(EditSeriesId id) {
		this.id = id;
	}

}
