package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * EditorWatchPreferences generated by hbm2java
 */
public class EditorWatchPreferences implements java.io.Serializable {

	private int editor;
	private boolean notifyViaEmail;
	private Serializable notificationTimeframe;
	private Date lastChecked;

	public EditorWatchPreferences() {
	}

	public EditorWatchPreferences(int editor, boolean notifyViaEmail,
			Serializable notificationTimeframe, Date lastChecked) {
		this.editor = editor;
		this.notifyViaEmail = notifyViaEmail;
		this.notificationTimeframe = notificationTimeframe;
		this.lastChecked = lastChecked;
	}

	public int getEditor() {
		return this.editor;
	}

	public void setEditor(int editor) {
		this.editor = editor;
	}

	public boolean isNotifyViaEmail() {
		return this.notifyViaEmail;
	}

	public void setNotifyViaEmail(boolean notifyViaEmail) {
		this.notifyViaEmail = notifyViaEmail;
	}

	public Serializable getNotificationTimeframe() {
		return this.notificationTimeframe;
	}

	public void setNotificationTimeframe(Serializable notificationTimeframe) {
		this.notificationTimeframe = notificationTimeframe;
	}

	public Date getLastChecked() {
		return this.lastChecked;
	}

	public void setLastChecked(Date lastChecked) {
		this.lastChecked = lastChecked;
	}

}
