package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditArea generated by hbm2java
 */
public class EditArea implements java.io.Serializable {

	private EditAreaId id;

	public EditArea() {
	}

	public EditArea(EditAreaId id) {
		this.id = id;
	}

	public EditAreaId getId() {
		return this.id;
	}

	public void setId(EditAreaId id) {
		this.id = id;
	}

}
