package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditorSubscribeArtistDeleted generated by hbm2java
 */
public class EditorSubscribeArtistDeleted implements java.io.Serializable {

	private EditorSubscribeArtistDeletedId id;
	private int deletedBy;

	public EditorSubscribeArtistDeleted() {
	}

	public EditorSubscribeArtistDeleted(EditorSubscribeArtistDeletedId id,
			int deletedBy) {
		this.id = id;
		this.deletedBy = deletedBy;
	}

	public EditorSubscribeArtistDeletedId getId() {
		return this.id;
	}

	public void setId(EditorSubscribeArtistDeletedId id) {
		this.id = id;
	}

	public int getDeletedBy() {
		return this.deletedBy;
	}

	public void setDeletedBy(int deletedBy) {
		this.deletedBy = deletedBy;
	}

}
