package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditorCollectionInstrument generated by hbm2java
 */
public class EditorCollectionInstrument implements java.io.Serializable {

	private EditorCollectionInstrumentId id;

	public EditorCollectionInstrument() {
	}

	public EditorCollectionInstrument(EditorCollectionInstrumentId id) {
		this.id = id;
	}

	public EditorCollectionInstrumentId getId() {
		return this.id;
	}

	public void setId(EditorCollectionInstrumentId id) {
		this.id = id;
	}

}
