package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditLabelId generated by hbm2java
 */
public class EditLabelId implements java.io.Serializable {

	private int edit;
	private int label;

	public EditLabelId() {
	}

	public EditLabelId(int edit, int label) {
		this.edit = edit;
		this.label = label;
	}

	public int getEdit() {
		return this.edit;
	}

	public void setEdit(int edit) {
		this.edit = edit;
	}

	public int getLabel() {
		return this.label;
	}

	public void setLabel(int label) {
		this.label = label;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EditLabelId))
			return false;
		EditLabelId castOther = (EditLabelId) other;

		return (this.getEdit() == castOther.getEdit())
				&& (this.getLabel() == castOther.getLabel());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEdit();
		result = 37 * result + this.getLabel();
		return result;
	}

}
