package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditorCollectionArea generated by hbm2java
 */
public class EditorCollectionArea implements java.io.Serializable {

	private EditorCollectionAreaId id;

	public EditorCollectionArea() {
	}

	public EditorCollectionArea(EditorCollectionAreaId id) {
		this.id = id;
	}

	public EditorCollectionAreaId getId() {
		return this.id;
	}

	public void setId(EditorCollectionAreaId id) {
		this.id = id;
	}

}
