package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditorCollectionSeries generated by hbm2java
 */
public class EditorCollectionSeries implements java.io.Serializable {

	private EditorCollectionSeriesId id;

	public EditorCollectionSeries() {
	}

	public EditorCollectionSeries(EditorCollectionSeriesId id) {
		this.id = id;
	}

	public EditorCollectionSeriesId getId() {
		return this.id;
	}

	public void setId(EditorCollectionSeriesId id) {
		this.id = id;
	}

}
