package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditUrl generated by hbm2java
 */
public class EditUrl implements java.io.Serializable {

	private EditUrlId id;

	public EditUrl() {
	}

	public EditUrl(EditUrlId id) {
		this.id = id;
	}

	public EditUrlId getId() {
		return this.id;
	}

	public void setId(EditUrlId id) {
		this.id = id;
	}

}
