package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditorCollectionArtist generated by hbm2java
 */
public class EditorCollectionArtist implements java.io.Serializable {

	private EditorCollectionArtistId id;

	public EditorCollectionArtist() {
	}

	public EditorCollectionArtist(EditorCollectionArtistId id) {
		this.id = id;
	}

	public EditorCollectionArtistId getId() {
		return this.id;
	}

	public void setId(EditorCollectionArtistId id) {
		this.id = id;
	}

}
