package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditRelease generated by hbm2java
 */
public class EditRelease implements java.io.Serializable {

	private EditReleaseId id;

	public EditRelease() {
	}

	public EditRelease(EditReleaseId id) {
		this.id = id;
	}

	public EditReleaseId getId() {
		return this.id;
	}

	public void setId(EditReleaseId id) {
		this.id = id;
	}

}
