package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditWork generated by hbm2java
 */
public class EditWork implements java.io.Serializable {

	private EditWorkId id;

	public EditWork() {
	}

	public EditWork(EditWorkId id) {
		this.id = id;
	}

	public EditWorkId getId() {
		return this.id;
	}

	public void setId(EditWorkId id) {
		this.id = id;
	}

}
