package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditorCollectionEventId generated by hbm2java
 */
public class EditorCollectionEventId implements java.io.Serializable {

	private int collection;
	private int event;

	public EditorCollectionEventId() {
	}

	public EditorCollectionEventId(int collection, int event) {
		this.collection = collection;
		this.event = event;
	}

	public int getCollection() {
		return this.collection;
	}

	public void setCollection(int collection) {
		this.collection = collection;
	}

	public int getEvent() {
		return this.event;
	}

	public void setEvent(int event) {
		this.event = event;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EditorCollectionEventId))
			return false;
		EditorCollectionEventId castOther = (EditorCollectionEventId) other;

		return (this.getCollection() == castOther.getCollection())
				&& (this.getEvent() == castOther.getEvent());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCollection();
		result = 37 * result + this.getEvent();
		return result;
	}

}
