package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditReleaseId generated by hbm2java
 */
public class EditReleaseId implements java.io.Serializable {

	private int edit;
	private int release;

	public EditReleaseId() {
	}

	public EditReleaseId(int edit, int release) {
		this.edit = edit;
		this.release = release;
	}

	public int getEdit() {
		return this.edit;
	}

	public void setEdit(int edit) {
		this.edit = edit;
	}

	public int getRelease() {
		return this.release;
	}

	public void setRelease(int release) {
		this.release = release;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EditReleaseId))
			return false;
		EditReleaseId castOther = (EditReleaseId) other;

		return (this.getEdit() == castOther.getEdit())
				&& (this.getRelease() == castOther.getRelease());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEdit();
		result = 37 * result + this.getRelease();
		return result;
	}

}
