package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * EditNote generated by hbm2java
 */
public class EditNote implements java.io.Serializable {

	private int id;
	private int editor;
	private int edit;
	private String text;
	private Date postTime;

	public EditNote() {
	}

	public EditNote(int id, int editor, int edit, String text) {
		this.id = id;
		this.editor = editor;
		this.edit = edit;
		this.text = text;
	}

	public EditNote(int id, int editor, int edit, String text, Date postTime) {
		this.id = id;
		this.editor = editor;
		this.edit = edit;
		this.text = text;
		this.postTime = postTime;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getEditor() {
		return this.editor;
	}

	public void setEditor(int editor) {
		this.editor = editor;
	}

	public int getEdit() {
		return this.edit;
	}

	public void setEdit(int edit) {
		this.edit = edit;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public Date getPostTime() {
		return this.postTime;
	}

	public void setPostTime(Date postTime) {
		this.postTime = postTime;
	}

}
