package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditPlaceId generated by hbm2java
 */
public class EditPlaceId implements java.io.Serializable {

	private int edit;
	private int place;

	public EditPlaceId() {
	}

	public EditPlaceId(int edit, int place) {
		this.edit = edit;
		this.place = place;
	}

	public int getEdit() {
		return this.edit;
	}

	public void setEdit(int edit) {
		this.edit = edit;
	}

	public int getPlace() {
		return this.place;
	}

	public void setPlace(int place) {
		this.place = place;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EditPlaceId))
			return false;
		EditPlaceId castOther = (EditPlaceId) other;

		return (this.getEdit() == castOther.getEdit())
				&& (this.getPlace() == castOther.getPlace());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEdit();
		result = 37 * result + this.getPlace();
		return result;
	}

}
