package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditorWatchArtist generated by hbm2java
 */
public class EditorWatchArtist implements java.io.Serializable {

	private EditorWatchArtistId id;

	public EditorWatchArtist() {
	}

	public EditorWatchArtist(EditorWatchArtistId id) {
		this.id = id;
	}

	public EditorWatchArtistId getId() {
		return this.id;
	}

	public void setId(EditorWatchArtistId id) {
		this.id = id;
	}

}
