package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditArtistId generated by hbm2java
 */
public class EditArtistId implements java.io.Serializable {

	private int edit;
	private int artist;

	public EditArtistId() {
	}

	public EditArtistId(int edit, int artist) {
		this.edit = edit;
		this.artist = artist;
	}

	public int getEdit() {
		return this.edit;
	}

	public void setEdit(int edit) {
		this.edit = edit;
	}

	public int getArtist() {
		return this.artist;
	}

	public void setArtist(int artist) {
		this.artist = artist;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EditArtistId))
			return false;
		EditArtistId castOther = (EditArtistId) other;

		return (this.getEdit() == castOther.getEdit())
				&& (this.getArtist() == castOther.getArtist());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEdit();
		result = 37 * result + this.getArtist();
		return result;
	}

}
