package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditorCollectionRecordingId generated by hbm2java
 */
public class EditorCollectionRecordingId implements java.io.Serializable {

	private int collection;
	private int recording;

	public EditorCollectionRecordingId() {
	}

	public EditorCollectionRecordingId(int collection, int recording) {
		this.collection = collection;
		this.recording = recording;
	}

	public int getCollection() {
		return this.collection;
	}

	public void setCollection(int collection) {
		this.collection = collection;
	}

	public int getRecording() {
		return this.recording;
	}

	public void setRecording(int recording) {
		this.recording = recording;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EditorCollectionRecordingId))
			return false;
		EditorCollectionRecordingId castOther = (EditorCollectionRecordingId) other;

		return (this.getCollection() == castOther.getCollection())
				&& (this.getRecording() == castOther.getRecording());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCollection();
		result = 37 * result + this.getRecording();
		return result;
	}

}
