package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditorSubscribeEditor generated by hbm2java
 */
public class EditorSubscribeEditor implements java.io.Serializable {

	private int id;
	private int editor;
	private int subscribedEditor;
	private int lastEditSent;

	public EditorSubscribeEditor() {
	}

	public EditorSubscribeEditor(int id, int editor, int subscribedEditor,
			int lastEditSent) {
		this.id = id;
		this.editor = editor;
		this.subscribedEditor = subscribedEditor;
		this.lastEditSent = lastEditSent;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getEditor() {
		return this.editor;
	}

	public void setEditor(int editor) {
		this.editor = editor;
	}

	public int getSubscribedEditor() {
		return this.subscribedEditor;
	}

	public void setSubscribedEditor(int subscribedEditor) {
		this.subscribedEditor = subscribedEditor;
	}

	public int getLastEditSent() {
		return this.lastEditSent;
	}

	public void setLastEditSent(int lastEditSent) {
		this.lastEditSent = lastEditSent;
	}

}
