package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditorCollectionLabelId generated by hbm2java
 */
public class EditorCollectionLabelId implements java.io.Serializable {

	private int collection;
	private int label;

	public EditorCollectionLabelId() {
	}

	public EditorCollectionLabelId(int collection, int label) {
		this.collection = collection;
		this.label = label;
	}

	public int getCollection() {
		return this.collection;
	}

	public void setCollection(int collection) {
		this.collection = collection;
	}

	public int getLabel() {
		return this.label;
	}

	public void setLabel(int label) {
		this.label = label;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EditorCollectionLabelId))
			return false;
		EditorCollectionLabelId castOther = (EditorCollectionLabelId) other;

		return (this.getCollection() == castOther.getCollection())
				&& (this.getLabel() == castOther.getLabel());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCollection();
		result = 37 * result + this.getLabel();
		return result;
	}

}
