package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditorCollectionWork generated by hbm2java
 */
public class EditorCollectionWork implements java.io.Serializable {

	private EditorCollectionWorkId id;

	public EditorCollectionWork() {
	}

	public EditorCollectionWork(EditorCollectionWorkId id) {
		this.id = id;
	}

	public EditorCollectionWorkId getId() {
		return this.id;
	}

	public void setId(EditorCollectionWorkId id) {
		this.id = id;
	}

}
