package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EventTagRawId generated by hbm2java
 */
public class EventTagRawId implements java.io.Serializable {

	private int event;
	private int editor;
	private int tag;

	public EventTagRawId() {
	}

	public EventTagRawId(int event, int editor, int tag) {
		this.event = event;
		this.editor = editor;
		this.tag = tag;
	}

	public int getEvent() {
		return this.event;
	}

	public void setEvent(int event) {
		this.event = event;
	}

	public int getEditor() {
		return this.editor;
	}

	public void setEditor(int editor) {
		this.editor = editor;
	}

	public int getTag() {
		return this.tag;
	}

	public void setTag(int tag) {
		this.tag = tag;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EventTagRawId))
			return false;
		EventTagRawId castOther = (EventTagRawId) other;

		return (this.getEvent() == castOther.getEvent())
				&& (this.getEditor() == castOther.getEditor())
				&& (this.getTag() == castOther.getTag());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEvent();
		result = 37 * result + this.getEditor();
		result = 37 * result + this.getTag();
		return result;
	}

}
