package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EventTagId generated by hbm2java
 */
public class EventTagId implements java.io.Serializable {

	private int event;
	private int tag;

	public EventTagId() {
	}

	public EventTagId(int event, int tag) {
		this.event = event;
		this.tag = tag;
	}

	public int getEvent() {
		return this.event;
	}

	public void setEvent(int event) {
		this.event = event;
	}

	public int getTag() {
		return this.tag;
	}

	public void setTag(int tag) {
		this.tag = tag;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EventTagId))
			return false;
		EventTagId castOther = (EventTagId) other;

		return (this.getEvent() == castOther.getEvent())
				&& (this.getTag() == castOther.getTag());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEvent();
		result = 37 * result + this.getTag();
		return result;
	}

}
