package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EventSeries generated by hbm2java
 */
public class EventSeries implements java.io.Serializable {

	private EventSeriesId id;

	public EventSeries() {
	}

	public EventSeries(EventSeriesId id) {
		this.id = id;
	}

	public EventSeriesId getId() {
		return this.id;
	}

	public void setId(EventSeriesId id) {
		this.id = id;
	}

}
