package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EventRatingRawId generated by hbm2java
 */
public class EventRatingRawId implements java.io.Serializable {

	private int event;
	private int editor;

	public EventRatingRawId() {
	}

	public EventRatingRawId(int event, int editor) {
		this.event = event;
		this.editor = editor;
	}

	public int getEvent() {
		return this.event;
	}

	public void setEvent(int event) {
		this.event = event;
	}

	public int getEditor() {
		return this.editor;
	}

	public void setEditor(int editor) {
		this.editor = editor;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EventRatingRawId))
			return false;
		EventRatingRawId castOther = (EventRatingRawId) other;

		return (this.getEvent() == castOther.getEvent())
				&& (this.getEditor() == castOther.getEditor());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEvent();
		result = 37 * result + this.getEditor();
		return result;
	}

}
