package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EventAnnotation generated by hbm2java
 */
public class EventAnnotation implements java.io.Serializable {

	private EventAnnotationId id;

	public EventAnnotation() {
	}

	public EventAnnotation(EventAnnotationId id) {
		this.id = id;
	}

	public EventAnnotationId getId() {
		return this.id;
	}

	public void setId(EventAnnotationId id) {
		this.id = id;
	}

}
