package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EventRatingRaw generated by hbm2java
 */
public class EventRatingRaw implements java.io.Serializable {

	private EventRatingRawId id;
	private short rating;

	public EventRatingRaw() {
	}

	public EventRatingRaw(EventRatingRawId id, short rating) {
		this.id = id;
		this.rating = rating;
	}

	public EventRatingRawId getId() {
		return this.id;
	}

	public void setId(EventRatingRawId id) {
		this.id = id;
	}

	public short getRating() {
		return this.rating;
	}

	public void setRating(short rating) {
		this.rating = rating;
	}

}
