package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * EventTagRaw generated by hbm2java
 */
public class EventTagRaw implements java.io.Serializable {

	private EventTagRawId id;
	private boolean isUpvote;

	public EventTagRaw() {
	}

	public EventTagRaw(EventTagRawId id, boolean isUpvote) {
		this.id = id;
		this.isUpvote = isUpvote;
	}

	public EventTagRawId getId() {
		return this.id;
	}

	public void setId(EventTagRawId id) {
		this.id = id;
	}

	public boolean isIsUpvote() {
		return this.isUpvote;
	}

	public void setIsUpvote(boolean isUpvote) {
		this.isUpvote = isUpvote;
	}

}
