package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * InstrumentTagId generated by hbm2java
 */
public class InstrumentTagId implements java.io.Serializable {

	private int instrument;
	private int tag;

	public InstrumentTagId() {
	}

	public InstrumentTagId(int instrument, int tag) {
		this.instrument = instrument;
		this.tag = tag;
	}

	public int getInstrument() {
		return this.instrument;
	}

	public void setInstrument(int instrument) {
		this.instrument = instrument;
	}

	public int getTag() {
		return this.tag;
	}

	public void setTag(int tag) {
		this.tag = tag;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InstrumentTagId))
			return false;
		InstrumentTagId castOther = (InstrumentTagId) other;

		return (this.getInstrument() == castOther.getInstrument())
				&& (this.getTag() == castOther.getTag());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getInstrument();
		result = 37 * result + this.getTag();
		return result;
	}

}
