package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * InstrumentTag generated by hbm2java
 */
public class InstrumentTag implements java.io.Serializable {

	private InstrumentTagId id;
	private int count;
	private Date lastUpdated;

	public InstrumentTag() {
	}

	public InstrumentTag(InstrumentTagId id, int count) {
		this.id = id;
		this.count = count;
	}

	public InstrumentTag(InstrumentTagId id, int count, Date lastUpdated) {
		this.id = id;
		this.count = count;
		this.lastUpdated = lastUpdated;
	}

	public InstrumentTagId getId() {
		return this.id;
	}

	public void setId(InstrumentTagId id) {
		this.id = id;
	}

	public int getCount() {
		return this.count;
	}

	public void setCount(int count) {
		this.count = count;
	}

	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

}
