package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * Instrument generated by hbm2java
 */
public class Instrument implements java.io.Serializable {

	private int id;
	private Serializable gid;
	private String name;
	private Integer type;
	private int editsPending;
	private Date lastUpdated;
	private String comment;
	private String description;

	public Instrument() {
	}

	public Instrument(int id, Serializable gid, String name, int editsPending,
			String comment, String description) {
		this.id = id;
		this.gid = gid;
		this.name = name;
		this.editsPending = editsPending;
		this.comment = comment;
		this.description = description;
	}

	public Instrument(int id, Serializable gid, String name, Integer type,
			int editsPending, Date lastUpdated, String comment,
			String description) {
		this.id = id;
		this.gid = gid;
		this.name = name;
		this.type = type;
		this.editsPending = editsPending;
		this.lastUpdated = lastUpdated;
		this.comment = comment;
		this.description = description;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Serializable getGid() {
		return this.gid;
	}

	public void setGid(Serializable gid) {
		this.gid = gid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public int getEditsPending() {
		return this.editsPending;
	}

	public void setEditsPending(int editsPending) {
		this.editsPending = editsPending;
	}

	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
