package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * InstrumentAnnotation generated by hbm2java
 */
public class InstrumentAnnotation implements java.io.Serializable {

	private InstrumentAnnotationId id;

	public InstrumentAnnotation() {
	}

	public InstrumentAnnotation(InstrumentAnnotationId id) {
		this.id = id;
	}

	public InstrumentAnnotationId getId() {
		return this.id;
	}

	public void setId(InstrumentAnnotationId id) {
		this.id = id;
	}

}
