package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Iswc generated by hbm2java
 */
public class Iswc implements java.io.Serializable {

	private int id;
	private int work;
	private String iswc;
	private Short source;
	private int editsPending;
	private Date created;

	public Iswc() {
	}

	public Iswc(int id, int work, int editsPending, Date created) {
		this.id = id;
		this.work = work;
		this.editsPending = editsPending;
		this.created = created;
	}

	public Iswc(int id, int work, String iswc, Short source, int editsPending,
			Date created) {
		this.id = id;
		this.work = work;
		this.iswc = iswc;
		this.source = source;
		this.editsPending = editsPending;
		this.created = created;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getWork() {
		return this.work;
	}

	public void setWork(int work) {
		this.work = work;
	}

	public String getIswc() {
		return this.iswc;
	}

	public void setIswc(String iswc) {
		this.iswc = iswc;
	}

	public Short getSource() {
		return this.source;
	}

	public void setSource(Short source) {
		this.source = source;
	}

	public int getEditsPending() {
		return this.editsPending;
	}

	public void setEditsPending(int editsPending) {
		this.editsPending = editsPending;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

}
