package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * LabelIsniId generated by hbm2java
 */
public class LabelIsniId implements java.io.Serializable {

	private int label;
	private String isni;

	public LabelIsniId() {
	}

	public LabelIsniId(int label, String isni) {
		this.label = label;
		this.isni = isni;
	}

	public int getLabel() {
		return this.label;
	}

	public void setLabel(int label) {
		this.label = label;
	}

	public String getIsni() {
		return this.isni;
	}

	public void setIsni(String isni) {
		this.isni = isni;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LabelIsniId))
			return false;
		LabelIsniId castOther = (LabelIsniId) other;

		return (this.getLabel() == castOther.getLabel())
				&& ((this.getIsni() == castOther.getIsni()) || (this.getIsni() != null
						&& castOther.getIsni() != null && this.getIsni()
						.equals(castOther.getIsni())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLabel();
		result = 37 * result
				+ (getIsni() == null ? 0 : this.getIsni().hashCode());
		return result;
	}

}
