package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * LabelTagRaw generated by hbm2java
 */
public class LabelTagRaw implements java.io.Serializable {

	private LabelTagRawId id;
	private boolean isUpvote;

	public LabelTagRaw() {
	}

	public LabelTagRaw(LabelTagRawId id, boolean isUpvote) {
		this.id = id;
		this.isUpvote = isUpvote;
	}

	public LabelTagRawId getId() {
		return this.id;
	}

	public void setId(LabelTagRawId id) {
		this.id = id;
	}

	public boolean isIsUpvote() {
		return this.isUpvote;
	}

	public void setIsUpvote(boolean isUpvote) {
		this.isUpvote = isUpvote;
	}

}
