package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * LabelIpi generated by hbm2java
 */
public class LabelIpi implements java.io.Serializable {

	private LabelIpiId id;
	private int editsPending;
	private Date created;

	public LabelIpi() {
	}

	public LabelIpi(LabelIpiId id, int editsPending) {
		this.id = id;
		this.editsPending = editsPending;
	}

	public LabelIpi(LabelIpiId id, int editsPending, Date created) {
		this.id = id;
		this.editsPending = editsPending;
		this.created = created;
	}

	public LabelIpiId getId() {
		return this.id;
	}

	public void setId(LabelIpiId id) {
		this.id = id;
	}

	public int getEditsPending() {
		return this.editsPending;
	}

	public void setEditsPending(int editsPending) {
		this.editsPending = editsPending;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

}
