package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * LabelRatingRaw generated by hbm2java
 */
public class LabelRatingRaw implements java.io.Serializable {

	private LabelRatingRawId id;
	private short rating;

	public LabelRatingRaw() {
	}

	public LabelRatingRaw(LabelRatingRawId id, short rating) {
		this.id = id;
		this.rating = rating;
	}

	public LabelRatingRawId getId() {
		return this.id;
	}

	public void setId(LabelRatingRawId id) {
		this.id = id;
	}

	public short getRating() {
		return this.rating;
	}

	public void setRating(short rating) {
		this.rating = rating;
	}

}
