package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * LabelTagRawId generated by hbm2java
 */
public class LabelTagRawId implements java.io.Serializable {

	private int label;
	private int editor;
	private int tag;

	public LabelTagRawId() {
	}

	public LabelTagRawId(int label, int editor, int tag) {
		this.label = label;
		this.editor = editor;
		this.tag = tag;
	}

	public int getLabel() {
		return this.label;
	}

	public void setLabel(int label) {
		this.label = label;
	}

	public int getEditor() {
		return this.editor;
	}

	public void setEditor(int editor) {
		this.editor = editor;
	}

	public int getTag() {
		return this.tag;
	}

	public void setTag(int tag) {
		this.tag = tag;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LabelTagRawId))
			return false;
		LabelTagRawId castOther = (LabelTagRawId) other;

		return (this.getLabel() == castOther.getLabel())
				&& (this.getEditor() == castOther.getEditor())
				&& (this.getTag() == castOther.getTag());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLabel();
		result = 37 * result + this.getEditor();
		result = 37 * result + this.getTag();
		return result;
	}

}
