package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * LabelAnnotation generated by hbm2java
 */
public class LabelAnnotation implements java.io.Serializable {

	private LabelAnnotationId id;

	public LabelAnnotation() {
	}

	public LabelAnnotation(LabelAnnotationId id) {
		this.id = id;
	}

	public LabelAnnotationId getId() {
		return this.id;
	}

	public void setId(LabelAnnotationId id) {
		this.id = id;
	}

}
