package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * LabelDeletion generated by hbm2java
 */
public class LabelDeletion implements java.io.Serializable {

	private Serializable gid;
	private String lastKnownName;
	private String lastKnownComment;
	private Date deletedAt;

	public LabelDeletion() {
	}

	public LabelDeletion(Serializable gid, String lastKnownName,
			String lastKnownComment, Date deletedAt) {
		this.gid = gid;
		this.lastKnownName = lastKnownName;
		this.lastKnownComment = lastKnownComment;
		this.deletedAt = deletedAt;
	}

	public Serializable getGid() {
		return this.gid;
	}

	public void setGid(Serializable gid) {
		this.gid = gid;
	}

	public String getLastKnownName() {
		return this.lastKnownName;
	}

	public void setLastKnownName(String lastKnownName) {
		this.lastKnownName = lastKnownName;
	}

	public String getLastKnownComment() {
		return this.lastKnownComment;
	}

	public void setLastKnownComment(String lastKnownComment) {
		this.lastKnownComment = lastKnownComment;
	}

	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

}
