package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * LabelMeta generated by hbm2java
 */
public class LabelMeta implements java.io.Serializable {

	private int id;
	private Short rating;
	private Integer ratingCount;

	public LabelMeta() {
	}

	public LabelMeta(int id) {
		this.id = id;
	}

	public LabelMeta(int id, Short rating, Integer ratingCount) {
		this.id = id;
		this.rating = rating;
		this.ratingCount = ratingCount;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Short getRating() {
		return this.rating;
	}

	public void setRating(Short rating) {
		this.rating = rating;
	}

	public Integer getRatingCount() {
		return this.ratingCount;
	}

	public void setRatingCount(Integer ratingCount) {
		this.ratingCount = ratingCount;
	}

}
