package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * LabelRatingRawId generated by hbm2java
 */
public class LabelRatingRawId implements java.io.Serializable {

	private int label;
	private int editor;

	public LabelRatingRawId() {
	}

	public LabelRatingRawId(int label, int editor) {
		this.label = label;
		this.editor = editor;
	}

	public int getLabel() {
		return this.label;
	}

	public void setLabel(int label) {
		this.label = label;
	}

	public int getEditor() {
		return this.editor;
	}

	public void setEditor(int editor) {
		this.editor = editor;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LabelRatingRawId))
			return false;
		LabelRatingRawId castOther = (LabelRatingRawId) other;

		return (this.getLabel() == castOther.getLabel())
				&& (this.getEditor() == castOther.getEditor());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLabel();
		result = 37 * result + this.getEditor();
		return result;
	}

}
