package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * LabelAnnotationId generated by hbm2java
 */
public class LabelAnnotationId implements java.io.Serializable {

	private int label;
	private int annotation;

	public LabelAnnotationId() {
	}

	public LabelAnnotationId(int label, int annotation) {
		this.label = label;
		this.annotation = annotation;
	}

	public int getLabel() {
		return this.label;
	}

	public void setLabel(int label) {
		this.label = label;
	}

	public int getAnnotation() {
		return this.annotation;
	}

	public void setAnnotation(int annotation) {
		this.annotation = annotation;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LabelAnnotationId))
			return false;
		LabelAnnotationId castOther = (LabelAnnotationId) other;

		return (this.getLabel() == castOther.getLabel())
				&& (this.getAnnotation() == castOther.getAnnotation());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLabel();
		result = 37 * result + this.getAnnotation();
		return result;
	}

}
