package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * Language generated by hbm2java
 */
public class Language implements java.io.Serializable {

	private int id;
	private String isoCode2t;
	private String isoCode2b;
	private String isoCode1;
	private String name;
	private int frequency;
	private String isoCode3;

	public Language() {
	}

	public Language(int id, String name, int frequency) {
		this.id = id;
		this.name = name;
		this.frequency = frequency;
	}

	public Language(int id, String isoCode2t, String isoCode2b,
			String isoCode1, String name, int frequency, String isoCode3) {
		this.id = id;
		this.isoCode2t = isoCode2t;
		this.isoCode2b = isoCode2b;
		this.isoCode1 = isoCode1;
		this.name = name;
		this.frequency = frequency;
		this.isoCode3 = isoCode3;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getIsoCode2t() {
		return this.isoCode2t;
	}

	public void setIsoCode2t(String isoCode2t) {
		this.isoCode2t = isoCode2t;
	}

	public String getIsoCode2b() {
		return this.isoCode2b;
	}

	public void setIsoCode2b(String isoCode2b) {
		this.isoCode2b = isoCode2b;
	}

	public String getIsoCode1() {
		return this.isoCode1;
	}

	public void setIsoCode1(String isoCode1) {
		this.isoCode1 = isoCode1;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getFrequency() {
		return this.frequency;
	}

	public void setFrequency(int frequency) {
		this.frequency = frequency;
	}

	public String getIsoCode3() {
		return this.isoCode3;
	}

	public void setIsoCode3(String isoCode3) {
		this.isoCode3 = isoCode3;
	}

}
