package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * LinkCreditableAttributeType generated by hbm2java
 */
public class LinkCreditableAttributeType implements java.io.Serializable {

	private int attributeType;

	public LinkCreditableAttributeType() {
	}

	public LinkCreditableAttributeType(int attributeType) {
		this.attributeType = attributeType;
	}

	public int getAttributeType() {
		return this.attributeType;
	}

	public void setAttributeType(int attributeType) {
		this.attributeType = attributeType;
	}

}
