package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * LinkTypeAttributeType generated by hbm2java
 */
public class LinkTypeAttributeType implements java.io.Serializable {

	private LinkTypeAttributeTypeId id;
	private Short min;
	private Short max;
	private Date lastUpdated;

	public LinkTypeAttributeType() {
	}

	public LinkTypeAttributeType(LinkTypeAttributeTypeId id) {
		this.id = id;
	}

	public LinkTypeAttributeType(LinkTypeAttributeTypeId id, Short min,
			Short max, Date lastUpdated) {
		this.id = id;
		this.min = min;
		this.max = max;
		this.lastUpdated = lastUpdated;
	}

	public LinkTypeAttributeTypeId getId() {
		return this.id;
	}

	public void setId(LinkTypeAttributeTypeId id) {
		this.id = id;
	}

	public Short getMin() {
		return this.min;
	}

	public void setMin(Short min) {
		this.min = min;
	}

	public Short getMax() {
		return this.max;
	}

	public void setMax(Short max) {
		this.max = max;
	}

	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

}
