package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * LinkAttributeTextValueId generated by hbm2java
 */
public class LinkAttributeTextValueId implements java.io.Serializable {

	private int link;
	private int attributeType;

	public LinkAttributeTextValueId() {
	}

	public LinkAttributeTextValueId(int link, int attributeType) {
		this.link = link;
		this.attributeType = attributeType;
	}

	public int getLink() {
		return this.link;
	}

	public void setLink(int link) {
		this.link = link;
	}

	public int getAttributeType() {
		return this.attributeType;
	}

	public void setAttributeType(int attributeType) {
		this.attributeType = attributeType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LinkAttributeTextValueId))
			return false;
		LinkAttributeTextValueId castOther = (LinkAttributeTextValueId) other;

		return (this.getLink() == castOther.getLink())
				&& (this.getAttributeType() == castOther.getAttributeType());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLink();
		result = 37 * result + this.getAttributeType();
		return result;
	}

}
