package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * LinkType generated by hbm2java
 */
public class LinkType implements java.io.Serializable {

	private int id;
	private Integer parent;
	private int childOrder;
	private Serializable gid;
	private String entityType0;
	private String entityType1;
	private String name;
	private String description;
	private String linkPhrase;
	private String reverseLinkPhrase;
	private String longLinkPhrase;
	private int priority;
	private Date lastUpdated;
	private boolean isDeprecated;
	private boolean hasDates;
	private int entity0Cardinality;
	private int entity1Cardinality;

	public LinkType() {
	}

	public LinkType(int id, int childOrder, Serializable gid,
			String entityType0, String entityType1, String name,
			String linkPhrase, String reverseLinkPhrase, String longLinkPhrase,
			int priority, boolean isDeprecated, boolean hasDates,
			int entity0Cardinality, int entity1Cardinality) {
		this.id = id;
		this.childOrder = childOrder;
		this.gid = gid;
		this.entityType0 = entityType0;
		this.entityType1 = entityType1;
		this.name = name;
		this.linkPhrase = linkPhrase;
		this.reverseLinkPhrase = reverseLinkPhrase;
		this.longLinkPhrase = longLinkPhrase;
		this.priority = priority;
		this.isDeprecated = isDeprecated;
		this.hasDates = hasDates;
		this.entity0Cardinality = entity0Cardinality;
		this.entity1Cardinality = entity1Cardinality;
	}

	public LinkType(int id, Integer parent, int childOrder, Serializable gid,
			String entityType0, String entityType1, String name,
			String description, String linkPhrase, String reverseLinkPhrase,
			String longLinkPhrase, int priority, Date lastUpdated,
			boolean isDeprecated, boolean hasDates, int entity0Cardinality,
			int entity1Cardinality) {
		this.id = id;
		this.parent = parent;
		this.childOrder = childOrder;
		this.gid = gid;
		this.entityType0 = entityType0;
		this.entityType1 = entityType1;
		this.name = name;
		this.description = description;
		this.linkPhrase = linkPhrase;
		this.reverseLinkPhrase = reverseLinkPhrase;
		this.longLinkPhrase = longLinkPhrase;
		this.priority = priority;
		this.lastUpdated = lastUpdated;
		this.isDeprecated = isDeprecated;
		this.hasDates = hasDates;
		this.entity0Cardinality = entity0Cardinality;
		this.entity1Cardinality = entity1Cardinality;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getParent() {
		return this.parent;
	}

	public void setParent(Integer parent) {
		this.parent = parent;
	}

	public int getChildOrder() {
		return this.childOrder;
	}

	public void setChildOrder(int childOrder) {
		this.childOrder = childOrder;
	}

	public Serializable getGid() {
		return this.gid;
	}

	public void setGid(Serializable gid) {
		this.gid = gid;
	}

	public String getEntityType0() {
		return this.entityType0;
	}

	public void setEntityType0(String entityType0) {
		this.entityType0 = entityType0;
	}

	public String getEntityType1() {
		return this.entityType1;
	}

	public void setEntityType1(String entityType1) {
		this.entityType1 = entityType1;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getLinkPhrase() {
		return this.linkPhrase;
	}

	public void setLinkPhrase(String linkPhrase) {
		this.linkPhrase = linkPhrase;
	}

	public String getReverseLinkPhrase() {
		return this.reverseLinkPhrase;
	}

	public void setReverseLinkPhrase(String reverseLinkPhrase) {
		this.reverseLinkPhrase = reverseLinkPhrase;
	}

	public String getLongLinkPhrase() {
		return this.longLinkPhrase;
	}

	public void setLongLinkPhrase(String longLinkPhrase) {
		this.longLinkPhrase = longLinkPhrase;
	}

	public int getPriority() {
		return this.priority;
	}

	public void setPriority(int priority) {
		this.priority = priority;
	}

	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	public boolean isIsDeprecated() {
		return this.isDeprecated;
	}

	public void setIsDeprecated(boolean isDeprecated) {
		this.isDeprecated = isDeprecated;
	}

	public boolean isHasDates() {
		return this.hasDates;
	}

	public void setHasDates(boolean hasDates) {
		this.hasDates = hasDates;
	}

	public int getEntity0Cardinality() {
		return this.entity0Cardinality;
	}

	public void setEntity0Cardinality(int entity0Cardinality) {
		this.entity0Cardinality = entity0Cardinality;
	}

	public int getEntity1Cardinality() {
		return this.entity1Cardinality;
	}

	public void setEntity1Cardinality(int entity1Cardinality) {
		this.entity1Cardinality = entity1Cardinality;
	}

}
