package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * LinkAttributeType generated by hbm2java
 */
public class LinkAttributeType implements java.io.Serializable {

	private int id;
	private Integer parent;
	private int root;
	private int childOrder;
	private Serializable gid;
	private String name;
	private String description;
	private Date lastUpdated;

	public LinkAttributeType() {
	}

	public LinkAttributeType(int id, int root, int childOrder,
			Serializable gid, String name) {
		this.id = id;
		this.root = root;
		this.childOrder = childOrder;
		this.gid = gid;
		this.name = name;
	}

	public LinkAttributeType(int id, Integer parent, int root, int childOrder,
			Serializable gid, String name, String description, Date lastUpdated) {
		this.id = id;
		this.parent = parent;
		this.root = root;
		this.childOrder = childOrder;
		this.gid = gid;
		this.name = name;
		this.description = description;
		this.lastUpdated = lastUpdated;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getParent() {
		return this.parent;
	}

	public void setParent(Integer parent) {
		this.parent = parent;
	}

	public int getRoot() {
		return this.root;
	}

	public void setRoot(int root) {
		this.root = root;
	}

	public int getChildOrder() {
		return this.childOrder;
	}

	public void setChildOrder(int childOrder) {
		this.childOrder = childOrder;
	}

	public Serializable getGid() {
		return this.gid;
	}

	public void setGid(Serializable gid) {
		this.gid = gid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

}
