package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * LinkAttribute generated by hbm2java
 */
public class LinkAttribute implements java.io.Serializable {

	private LinkAttributeId id;
	private Date created;

	public LinkAttribute() {
	}

	public LinkAttribute(LinkAttributeId id) {
		this.id = id;
	}

	public LinkAttribute(LinkAttributeId id, Date created) {
		this.id = id;
		this.created = created;
	}

	public LinkAttributeId getId() {
		return this.id;
	}

	public void setId(LinkAttributeId id) {
		this.id = id;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

}
