package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * LinkAttributeTextValue generated by hbm2java
 */
public class LinkAttributeTextValue implements java.io.Serializable {

	private LinkAttributeTextValueId id;
	private String textValue;

	public LinkAttributeTextValue() {
	}

	public LinkAttributeTextValue(LinkAttributeTextValueId id, String textValue) {
		this.id = id;
		this.textValue = textValue;
	}

	public LinkAttributeTextValueId getId() {
		return this.id;
	}

	public void setId(LinkAttributeTextValueId id) {
		this.id = id;
	}

	public String getTextValue() {
		return this.textValue;
	}

	public void setTextValue(String textValue) {
		this.textValue = textValue;
	}

}
