package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * LinkAttributeCredit generated by hbm2java
 */
public class LinkAttributeCredit implements java.io.Serializable {

	private LinkAttributeCreditId id;
	private String creditedAs;

	public LinkAttributeCredit() {
	}

	public LinkAttributeCredit(LinkAttributeCreditId id, String creditedAs) {
		this.id = id;
		this.creditedAs = creditedAs;
	}

	public LinkAttributeCreditId getId() {
		return this.id;
	}

	public void setId(LinkAttributeCreditId id) {
		this.id = id;
	}

	public String getCreditedAs() {
		return this.creditedAs;
	}

	public void setCreditedAs(String creditedAs) {
		this.creditedAs = creditedAs;
	}

}
