package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * MediumIndex generated by hbm2java
 */
public class MediumIndex implements java.io.Serializable {

	private int medium;
	private Serializable toc;

	public MediumIndex() {
	}

	public MediumIndex(int medium) {
		this.medium = medium;
	}

	public MediumIndex(int medium, Serializable toc) {
		this.medium = medium;
		this.toc = toc;
	}

	public int getMedium() {
		return this.medium;
	}

	public void setMedium(int medium) {
		this.medium = medium;
	}

	public Serializable getToc() {
		return this.toc;
	}

	public void setToc(Serializable toc) {
		this.toc = toc;
	}

}
