package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Medium generated by hbm2java
 */
public class Medium implements java.io.Serializable {

	private int id;
	private int release;
	private int position;
	private Integer format;
	private String name;
	private int editsPending;
	private Date lastUpdated;
	private int trackCount;

	public Medium() {
	}

	public Medium(int id, int release, int position, String name,
			int editsPending, int trackCount) {
		this.id = id;
		this.release = release;
		this.position = position;
		this.name = name;
		this.editsPending = editsPending;
		this.trackCount = trackCount;
	}

	public Medium(int id, int release, int position, Integer format,
			String name, int editsPending, Date lastUpdated, int trackCount) {
		this.id = id;
		this.release = release;
		this.position = position;
		this.format = format;
		this.name = name;
		this.editsPending = editsPending;
		this.lastUpdated = lastUpdated;
		this.trackCount = trackCount;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getRelease() {
		return this.release;
	}

	public void setRelease(int release) {
		this.release = release;
	}

	public int getPosition() {
		return this.position;
	}

	public void setPosition(int position) {
		this.position = position;
	}

	public Integer getFormat() {
		return this.format;
	}

	public void setFormat(Integer format) {
		this.format = format;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getEditsPending() {
		return this.editsPending;
	}

	public void setEditsPending(int editsPending) {
		this.editsPending = editsPending;
	}

	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	public int getTrackCount() {
		return this.trackCount;
	}

	public void setTrackCount(int trackCount) {
		this.trackCount = trackCount;
	}

}
