package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * MediumCdtoc generated by hbm2java
 */
public class MediumCdtoc implements java.io.Serializable {

	private int id;
	private int medium;
	private int cdtoc;
	private int editsPending;
	private Date lastUpdated;

	public MediumCdtoc() {
	}

	public MediumCdtoc(int id, int medium, int cdtoc, int editsPending) {
		this.id = id;
		this.medium = medium;
		this.cdtoc = cdtoc;
		this.editsPending = editsPending;
	}

	public MediumCdtoc(int id, int medium, int cdtoc, int editsPending,
			Date lastUpdated) {
		this.id = id;
		this.medium = medium;
		this.cdtoc = cdtoc;
		this.editsPending = editsPending;
		this.lastUpdated = lastUpdated;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getMedium() {
		return this.medium;
	}

	public void setMedium(int medium) {
		this.medium = medium;
	}

	public int getCdtoc() {
		return this.cdtoc;
	}

	public void setCdtoc(int cdtoc) {
		this.cdtoc = cdtoc;
	}

	public int getEditsPending() {
		return this.editsPending;
	}

	public void setEditsPending(int editsPending) {
		this.editsPending = editsPending;
	}

	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

}
