package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * PlaceAnnotation generated by hbm2java
 */
public class PlaceAnnotation implements java.io.Serializable {

	private PlaceAnnotationId id;

	public PlaceAnnotation() {
	}

	public PlaceAnnotation(PlaceAnnotationId id) {
		this.id = id;
	}

	public PlaceAnnotationId getId() {
		return this.id;
	}

	public void setId(PlaceAnnotationId id) {
		this.id = id;
	}

}
