package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * PlaceTagId generated by hbm2java
 */
public class PlaceTagId implements java.io.Serializable {

	private int place;
	private int tag;

	public PlaceTagId() {
	}

	public PlaceTagId(int place, int tag) {
		this.place = place;
		this.tag = tag;
	}

	public int getPlace() {
		return this.place;
	}

	public void setPlace(int place) {
		this.place = place;
	}

	public int getTag() {
		return this.tag;
	}

	public void setTag(int tag) {
		this.tag = tag;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PlaceTagId))
			return false;
		PlaceTagId castOther = (PlaceTagId) other;

		return (this.getPlace() == castOther.getPlace())
				&& (this.getTag() == castOther.getTag());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPlace();
		result = 37 * result + this.getTag();
		return result;
	}

}
