package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * RecordingTagId generated by hbm2java
 */
public class RecordingTagId implements java.io.Serializable {

	private int recording;
	private int tag;

	public RecordingTagId() {
	}

	public RecordingTagId(int recording, int tag) {
		this.recording = recording;
		this.tag = tag;
	}

	public int getRecording() {
		return this.recording;
	}

	public void setRecording(int recording) {
		this.recording = recording;
	}

	public int getTag() {
		return this.tag;
	}

	public void setTag(int tag) {
		this.tag = tag;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RecordingTagId))
			return false;
		RecordingTagId castOther = (RecordingTagId) other;

		return (this.getRecording() == castOther.getRecording())
				&& (this.getTag() == castOther.getTag());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRecording();
		result = 37 * result + this.getTag();
		return result;
	}

}
