package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * RecordingAnnotation generated by hbm2java
 */
public class RecordingAnnotation implements java.io.Serializable {

	private RecordingAnnotationId id;

	public RecordingAnnotation() {
	}

	public RecordingAnnotation(RecordingAnnotationId id) {
		this.id = id;
	}

	public RecordingAnnotationId getId() {
		return this.id;
	}

	public void setId(RecordingAnnotationId id) {
		this.id = id;
	}

}
