package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * RecordingAnnotationId generated by hbm2java
 */
public class RecordingAnnotationId implements java.io.Serializable {

	private int recording;
	private int annotation;

	public RecordingAnnotationId() {
	}

	public RecordingAnnotationId(int recording, int annotation) {
		this.recording = recording;
		this.annotation = annotation;
	}

	public int getRecording() {
		return this.recording;
	}

	public void setRecording(int recording) {
		this.recording = recording;
	}

	public int getAnnotation() {
		return this.annotation;
	}

	public void setAnnotation(int annotation) {
		this.annotation = annotation;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RecordingAnnotationId))
			return false;
		RecordingAnnotationId castOther = (RecordingAnnotationId) other;

		return (this.getRecording() == castOther.getRecording())
				&& (this.getAnnotation() == castOther.getAnnotation());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRecording();
		result = 37 * result + this.getAnnotation();
		return result;
	}

}
