package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * RecordingRatingRaw generated by hbm2java
 */
public class RecordingRatingRaw implements java.io.Serializable {

	private RecordingRatingRawId id;
	private short rating;

	public RecordingRatingRaw() {
	}

	public RecordingRatingRaw(RecordingRatingRawId id, short rating) {
		this.id = id;
		this.rating = rating;
	}

	public RecordingRatingRawId getId() {
		return this.id;
	}

	public void setId(RecordingRatingRawId id) {
		this.id = id;
	}

	public short getRating() {
		return this.rating;
	}

	public void setRating(short rating) {
		this.rating = rating;
	}

}
