package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * RecordingSeries generated by hbm2java
 */
public class RecordingSeries implements java.io.Serializable {

	private RecordingSeriesId id;

	public RecordingSeries() {
	}

	public RecordingSeries(RecordingSeriesId id) {
		this.id = id;
	}

	public RecordingSeriesId getId() {
		return this.id;
	}

	public void setId(RecordingSeriesId id) {
		this.id = id;
	}

}
