package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * RecordingRatingRawId generated by hbm2java
 */
public class RecordingRatingRawId implements java.io.Serializable {

	private int recording;
	private int editor;

	public RecordingRatingRawId() {
	}

	public RecordingRatingRawId(int recording, int editor) {
		this.recording = recording;
		this.editor = editor;
	}

	public int getRecording() {
		return this.recording;
	}

	public void setRecording(int recording) {
		this.recording = recording;
	}

	public int getEditor() {
		return this.editor;
	}

	public void setEditor(int editor) {
		this.editor = editor;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RecordingRatingRawId))
			return false;
		RecordingRatingRawId castOther = (RecordingRatingRawId) other;

		return (this.getRecording() == castOther.getRecording())
				&& (this.getEditor() == castOther.getEditor());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRecording();
		result = 37 * result + this.getEditor();
		return result;
	}

}
