package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * Recording generated by hbm2java
 */
public class Recording implements java.io.Serializable {

	private int id;
	private Serializable gid;
	private String name;
	private int artistCredit;
	private Integer length;
	private String comment;
	private int editsPending;
	private Date lastUpdated;
	private boolean video;

	public Recording() {
	}

	public Recording(int id, Serializable gid, String name, int artistCredit,
			String comment, int editsPending, boolean video) {
		this.id = id;
		this.gid = gid;
		this.name = name;
		this.artistCredit = artistCredit;
		this.comment = comment;
		this.editsPending = editsPending;
		this.video = video;
	}

	public Recording(int id, Serializable gid, String name, int artistCredit,
			Integer length, String comment, int editsPending, Date lastUpdated,
			boolean video) {
		this.id = id;
		this.gid = gid;
		this.name = name;
		this.artistCredit = artistCredit;
		this.length = length;
		this.comment = comment;
		this.editsPending = editsPending;
		this.lastUpdated = lastUpdated;
		this.video = video;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Serializable getGid() {
		return this.gid;
	}

	public void setGid(Serializable gid) {
		this.gid = gid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getArtistCredit() {
		return this.artistCredit;
	}

	public void setArtistCredit(int artistCredit) {
		this.artistCredit = artistCredit;
	}

	public Integer getLength() {
		return this.length;
	}

	public void setLength(Integer length) {
		this.length = length;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public int getEditsPending() {
		return this.editsPending;
	}

	public void setEditsPending(int editsPending) {
		this.editsPending = editsPending;
	}

	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	public boolean isVideo() {
		return this.video;
	}

	public void setVideo(boolean video) {
		this.video = video;
	}

}
