package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * ReleaseCountry generated by hbm2java
 */
public class ReleaseCountry implements java.io.Serializable {

	private ReleaseCountryId id;
	private Short dateYear;
	private Short dateMonth;
	private Short dateDay;

	public ReleaseCountry() {
	}

	public ReleaseCountry(ReleaseCountryId id) {
		this.id = id;
	}

	public ReleaseCountry(ReleaseCountryId id, Short dateYear, Short dateMonth,
			Short dateDay) {
		this.id = id;
		this.dateYear = dateYear;
		this.dateMonth = dateMonth;
		this.dateDay = dateDay;
	}

	public ReleaseCountryId getId() {
		return this.id;
	}

	public void setId(ReleaseCountryId id) {
		this.id = id;
	}

	public Short getDateYear() {
		return this.dateYear;
	}

	public void setDateYear(Short dateYear) {
		this.dateYear = dateYear;
	}

	public Short getDateMonth() {
		return this.dateMonth;
	}

	public void setDateMonth(Short dateMonth) {
		this.dateMonth = dateMonth;
	}

	public Short getDateDay() {
		return this.dateDay;
	}

	public void setDateDay(Short dateDay) {
		this.dateDay = dateDay;
	}

}
