package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * ReleaseGroupRatingRaw generated by hbm2java
 */
public class ReleaseGroupRatingRaw implements java.io.Serializable {

	private ReleaseGroupRatingRawId id;
	private short rating;

	public ReleaseGroupRatingRaw() {
	}

	public ReleaseGroupRatingRaw(ReleaseGroupRatingRawId id, short rating) {
		this.id = id;
		this.rating = rating;
	}

	public ReleaseGroupRatingRawId getId() {
		return this.id;
	}

	public void setId(ReleaseGroupRatingRawId id) {
		this.id = id;
	}

	public short getRating() {
		return this.rating;
	}

	public void setRating(short rating) {
		this.rating = rating;
	}

}
