package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * ReleaseGroupSecondaryTypeJoinId generated by hbm2java
 */
public class ReleaseGroupSecondaryTypeJoinId implements java.io.Serializable {

	private int releaseGroup;
	private int secondaryType;

	public ReleaseGroupSecondaryTypeJoinId() {
	}

	public ReleaseGroupSecondaryTypeJoinId(int releaseGroup, int secondaryType) {
		this.releaseGroup = releaseGroup;
		this.secondaryType = secondaryType;
	}

	public int getReleaseGroup() {
		return this.releaseGroup;
	}

	public void setReleaseGroup(int releaseGroup) {
		this.releaseGroup = releaseGroup;
	}

	public int getSecondaryType() {
		return this.secondaryType;
	}

	public void setSecondaryType(int secondaryType) {
		this.secondaryType = secondaryType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReleaseGroupSecondaryTypeJoinId))
			return false;
		ReleaseGroupSecondaryTypeJoinId castOther = (ReleaseGroupSecondaryTypeJoinId) other;

		return (this.getReleaseGroup() == castOther.getReleaseGroup())
				&& (this.getSecondaryType() == castOther.getSecondaryType());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getReleaseGroup();
		result = 37 * result + this.getSecondaryType();
		return result;
	}

}
