package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ReleaseTag generated by hbm2java
 */
public class ReleaseTag implements java.io.Serializable {

	private ReleaseTagId id;
	private int count;
	private Date lastUpdated;

	public ReleaseTag() {
	}

	public ReleaseTag(ReleaseTagId id, int count) {
		this.id = id;
		this.count = count;
	}

	public ReleaseTag(ReleaseTagId id, int count, Date lastUpdated) {
		this.id = id;
		this.count = count;
		this.lastUpdated = lastUpdated;
	}

	public ReleaseTagId getId() {
		return this.id;
	}

	public void setId(ReleaseTagId id) {
		this.id = id;
	}

	public int getCount() {
		return this.count;
	}

	public void setCount(int count) {
		this.count = count;
	}

	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

}
