package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * ReleaseGroupMeta generated by hbm2java
 */
public class ReleaseGroupMeta implements java.io.Serializable {

	private int id;
	private int releaseCount;
	private Short firstReleaseDateYear;
	private Short firstReleaseDateMonth;
	private Short firstReleaseDateDay;
	private Short rating;
	private Integer ratingCount;

	public ReleaseGroupMeta() {
	}

	public ReleaseGroupMeta(int id, int releaseCount) {
		this.id = id;
		this.releaseCount = releaseCount;
	}

	public ReleaseGroupMeta(int id, int releaseCount,
			Short firstReleaseDateYear, Short firstReleaseDateMonth,
			Short firstReleaseDateDay, Short rating, Integer ratingCount) {
		this.id = id;
		this.releaseCount = releaseCount;
		this.firstReleaseDateYear = firstReleaseDateYear;
		this.firstReleaseDateMonth = firstReleaseDateMonth;
		this.firstReleaseDateDay = firstReleaseDateDay;
		this.rating = rating;
		this.ratingCount = ratingCount;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getReleaseCount() {
		return this.releaseCount;
	}

	public void setReleaseCount(int releaseCount) {
		this.releaseCount = releaseCount;
	}

	public Short getFirstReleaseDateYear() {
		return this.firstReleaseDateYear;
	}

	public void setFirstReleaseDateYear(Short firstReleaseDateYear) {
		this.firstReleaseDateYear = firstReleaseDateYear;
	}

	public Short getFirstReleaseDateMonth() {
		return this.firstReleaseDateMonth;
	}

	public void setFirstReleaseDateMonth(Short firstReleaseDateMonth) {
		this.firstReleaseDateMonth = firstReleaseDateMonth;
	}

	public Short getFirstReleaseDateDay() {
		return this.firstReleaseDateDay;
	}

	public void setFirstReleaseDateDay(Short firstReleaseDateDay) {
		this.firstReleaseDateDay = firstReleaseDateDay;
	}

	public Short getRating() {
		return this.rating;
	}

	public void setRating(Short rating) {
		this.rating = rating;
	}

	public Integer getRatingCount() {
		return this.ratingCount;
	}

	public void setRatingCount(Integer ratingCount) {
		this.ratingCount = ratingCount;
	}

}
