package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ReleaseGroupSecondaryTypeJoin generated by hbm2java
 */
public class ReleaseGroupSecondaryTypeJoin implements java.io.Serializable {

	private ReleaseGroupSecondaryTypeJoinId id;
	private Date created;

	public ReleaseGroupSecondaryTypeJoin() {
	}

	public ReleaseGroupSecondaryTypeJoin(ReleaseGroupSecondaryTypeJoinId id,
			Date created) {
		this.id = id;
		this.created = created;
	}

	public ReleaseGroupSecondaryTypeJoinId getId() {
		return this.id;
	}

	public void setId(ReleaseGroupSecondaryTypeJoinId id) {
		this.id = id;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

}
