package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * ReleaseGroupRatingRawId generated by hbm2java
 */
public class ReleaseGroupRatingRawId implements java.io.Serializable {

	private int releaseGroup;
	private int editor;

	public ReleaseGroupRatingRawId() {
	}

	public ReleaseGroupRatingRawId(int releaseGroup, int editor) {
		this.releaseGroup = releaseGroup;
		this.editor = editor;
	}

	public int getReleaseGroup() {
		return this.releaseGroup;
	}

	public void setReleaseGroup(int releaseGroup) {
		this.releaseGroup = releaseGroup;
	}

	public int getEditor() {
		return this.editor;
	}

	public void setEditor(int editor) {
		this.editor = editor;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReleaseGroupRatingRawId))
			return false;
		ReleaseGroupRatingRawId castOther = (ReleaseGroupRatingRawId) other;

		return (this.getReleaseGroup() == castOther.getReleaseGroup())
				&& (this.getEditor() == castOther.getEditor());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getReleaseGroup();
		result = 37 * result + this.getEditor();
		return result;
	}

}
