package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * ReleaseAnnotation generated by hbm2java
 */
public class ReleaseAnnotation implements java.io.Serializable {

	private ReleaseAnnotationId id;

	public ReleaseAnnotation() {
	}

	public ReleaseAnnotation(ReleaseAnnotationId id) {
		this.id = id;
	}

	public ReleaseAnnotationId getId() {
		return this.id;
	}

	public void setId(ReleaseAnnotationId id) {
		this.id = id;
	}

}
