package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * ReleaseSeries generated by hbm2java
 */
public class ReleaseSeries implements java.io.Serializable {

	private ReleaseSeriesId id;

	public ReleaseSeries() {
	}

	public ReleaseSeries(ReleaseSeriesId id) {
		this.id = id;
	}

	public ReleaseSeriesId getId() {
		return this.id;
	}

	public void setId(ReleaseSeriesId id) {
		this.id = id;
	}

}
