package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ReleaseLabel generated by hbm2java
 */
public class ReleaseLabel implements java.io.Serializable {

	private int id;
	private int release;
	private Integer label;
	private String catalogNumber;
	private Date lastUpdated;

	public ReleaseLabel() {
	}

	public ReleaseLabel(int id, int release) {
		this.id = id;
		this.release = release;
	}

	public ReleaseLabel(int id, int release, Integer label,
			String catalogNumber, Date lastUpdated) {
		this.id = id;
		this.release = release;
		this.label = label;
		this.catalogNumber = catalogNumber;
		this.lastUpdated = lastUpdated;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getRelease() {
		return this.release;
	}

	public void setRelease(int release) {
		this.release = release;
	}

	public Integer getLabel() {
		return this.label;
	}

	public void setLabel(Integer label) {
		this.label = label;
	}

	public String getCatalogNumber() {
		return this.catalogNumber;
	}

	public void setCatalogNumber(String catalogNumber) {
		this.catalogNumber = catalogNumber;
	}

	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

}
