package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * ReleaseGroupTagRaw generated by hbm2java
 */
public class ReleaseGroupTagRaw implements java.io.Serializable {

	private ReleaseGroupTagRawId id;
	private boolean isUpvote;

	public ReleaseGroupTagRaw() {
	}

	public ReleaseGroupTagRaw(ReleaseGroupTagRawId id, boolean isUpvote) {
		this.id = id;
		this.isUpvote = isUpvote;
	}

	public ReleaseGroupTagRawId getId() {
		return this.id;
	}

	public void setId(ReleaseGroupTagRawId id) {
		this.id = id;
	}

	public boolean isIsUpvote() {
		return this.isUpvote;
	}

	public void setIsUpvote(boolean isUpvote) {
		this.isUpvote = isUpvote;
	}

}
