package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * ReleaseGroupTagId generated by hbm2java
 */
public class ReleaseGroupTagId implements java.io.Serializable {

	private int releaseGroup;
	private int tag;

	public ReleaseGroupTagId() {
	}

	public ReleaseGroupTagId(int releaseGroup, int tag) {
		this.releaseGroup = releaseGroup;
		this.tag = tag;
	}

	public int getReleaseGroup() {
		return this.releaseGroup;
	}

	public void setReleaseGroup(int releaseGroup) {
		this.releaseGroup = releaseGroup;
	}

	public int getTag() {
		return this.tag;
	}

	public void setTag(int tag) {
		this.tag = tag;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReleaseGroupTagId))
			return false;
		ReleaseGroupTagId castOther = (ReleaseGroupTagId) other;

		return (this.getReleaseGroup() == castOther.getReleaseGroup())
				&& (this.getTag() == castOther.getTag());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getReleaseGroup();
		result = 37 * result + this.getTag();
		return result;
	}

}
