package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ReleaseCoverart generated by hbm2java
 */
public class ReleaseCoverart implements java.io.Serializable {

	private int id;
	private Date lastUpdated;
	private String coverArtUrl;

	public ReleaseCoverart() {
	}

	public ReleaseCoverart(int id) {
		this.id = id;
	}

	public ReleaseCoverart(int id, Date lastUpdated, String coverArtUrl) {
		this.id = id;
		this.lastUpdated = lastUpdated;
		this.coverArtUrl = coverArtUrl;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	public String getCoverArtUrl() {
		return this.coverArtUrl;
	}

	public void setCoverArtUrl(String coverArtUrl) {
		this.coverArtUrl = coverArtUrl;
	}

}
