package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * ReleaseTagRawId generated by hbm2java
 */
public class ReleaseTagRawId implements java.io.Serializable {

	private int release;
	private int editor;
	private int tag;

	public ReleaseTagRawId() {
	}

	public ReleaseTagRawId(int release, int editor, int tag) {
		this.release = release;
		this.editor = editor;
		this.tag = tag;
	}

	public int getRelease() {
		return this.release;
	}

	public void setRelease(int release) {
		this.release = release;
	}

	public int getEditor() {
		return this.editor;
	}

	public void setEditor(int editor) {
		this.editor = editor;
	}

	public int getTag() {
		return this.tag;
	}

	public void setTag(int tag) {
		this.tag = tag;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReleaseTagRawId))
			return false;
		ReleaseTagRawId castOther = (ReleaseTagRawId) other;

		return (this.getRelease() == castOther.getRelease())
				&& (this.getEditor() == castOther.getEditor())
				&& (this.getTag() == castOther.getTag());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRelease();
		result = 37 * result + this.getEditor();
		result = 37 * result + this.getTag();
		return result;
	}

}
