package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * ReleaseMeta generated by hbm2java
 */
public class ReleaseMeta implements java.io.Serializable {

	private int id;
	private Date dateAdded;
	private String infoUrl;
	private String amazonAsin;
	private String amazonStore;
	private Serializable coverArtPresence;

	public ReleaseMeta() {
	}

	public ReleaseMeta(int id, Serializable coverArtPresence) {
		this.id = id;
		this.coverArtPresence = coverArtPresence;
	}

	public ReleaseMeta(int id, Date dateAdded, String infoUrl,
			String amazonAsin, String amazonStore, Serializable coverArtPresence) {
		this.id = id;
		this.dateAdded = dateAdded;
		this.infoUrl = infoUrl;
		this.amazonAsin = amazonAsin;
		this.amazonStore = amazonStore;
		this.coverArtPresence = coverArtPresence;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

	public String getInfoUrl() {
		return this.infoUrl;
	}

	public void setInfoUrl(String infoUrl) {
		this.infoUrl = infoUrl;
	}

	public String getAmazonAsin() {
		return this.amazonAsin;
	}

	public void setAmazonAsin(String amazonAsin) {
		this.amazonAsin = amazonAsin;
	}

	public String getAmazonStore() {
		return this.amazonStore;
	}

	public void setAmazonStore(String amazonStore) {
		this.amazonStore = amazonStore;
	}

	public Serializable getCoverArtPresence() {
		return this.coverArtPresence;
	}

	public void setCoverArtPresence(Serializable coverArtPresence) {
		this.coverArtPresence = coverArtPresence;
	}

}
