package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * ReleaseGroupAnnotation generated by hbm2java
 */
public class ReleaseGroupAnnotation implements java.io.Serializable {

	private ReleaseGroupAnnotationId id;

	public ReleaseGroupAnnotation() {
	}

	public ReleaseGroupAnnotation(ReleaseGroupAnnotationId id) {
		this.id = id;
	}

	public ReleaseGroupAnnotationId getId() {
		return this.id;
	}

	public void setId(ReleaseGroupAnnotationId id) {
		this.id = id;
	}

}
