package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * ReleaseTagId generated by hbm2java
 */
public class ReleaseTagId implements java.io.Serializable {

	private int release;
	private int tag;

	public ReleaseTagId() {
	}

	public ReleaseTagId(int release, int tag) {
		this.release = release;
		this.tag = tag;
	}

	public int getRelease() {
		return this.release;
	}

	public void setRelease(int release) {
		this.release = release;
	}

	public int getTag() {
		return this.tag;
	}

	public void setTag(int tag) {
		this.tag = tag;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReleaseTagId))
			return false;
		ReleaseTagId castOther = (ReleaseTagId) other;

		return (this.getRelease() == castOther.getRelease())
				&& (this.getTag() == castOther.getTag());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRelease();
		result = 37 * result + this.getTag();
		return result;
	}

}
