package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * ReleaseAnnotationId generated by hbm2java
 */
public class ReleaseAnnotationId implements java.io.Serializable {

	private int release;
	private int annotation;

	public ReleaseAnnotationId() {
	}

	public ReleaseAnnotationId(int release, int annotation) {
		this.release = release;
		this.annotation = annotation;
	}

	public int getRelease() {
		return this.release;
	}

	public void setRelease(int release) {
		this.release = release;
	}

	public int getAnnotation() {
		return this.annotation;
	}

	public void setAnnotation(int annotation) {
		this.annotation = annotation;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReleaseAnnotationId))
			return false;
		ReleaseAnnotationId castOther = (ReleaseAnnotationId) other;

		return (this.getRelease() == castOther.getRelease())
				&& (this.getAnnotation() == castOther.getAnnotation());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRelease();
		result = 37 * result + this.getAnnotation();
		return result;
	}

}
