package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * ReleaseUnknownCountry generated by hbm2java
 */
public class ReleaseUnknownCountry implements java.io.Serializable {

	private int release;
	private Short dateYear;
	private Short dateMonth;
	private Short dateDay;

	public ReleaseUnknownCountry() {
	}

	public ReleaseUnknownCountry(int release) {
		this.release = release;
	}

	public ReleaseUnknownCountry(int release, Short dateYear, Short dateMonth,
			Short dateDay) {
		this.release = release;
		this.dateYear = dateYear;
		this.dateMonth = dateMonth;
		this.dateDay = dateDay;
	}

	public int getRelease() {
		return this.release;
	}

	public void setRelease(int release) {
		this.release = release;
	}

	public Short getDateYear() {
		return this.dateYear;
	}

	public void setDateYear(Short dateYear) {
		this.dateYear = dateYear;
	}

	public Short getDateMonth() {
		return this.dateMonth;
	}

	public void setDateMonth(Short dateMonth) {
		this.dateMonth = dateMonth;
	}

	public Short getDateDay() {
		return this.dateDay;
	}

	public void setDateDay(Short dateDay) {
		this.dateDay = dateDay;
	}

}
