package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * Release generated by hbm2java
 */
public class Release implements java.io.Serializable {

	private int id;
	private Serializable gid;
	private String name;
	private int artistCredit;
	private int releaseGroup;
	private Integer status;
	private Integer packaging;
	private Integer language;
	private Integer script;
	private String barcode;
	private String comment;
	private int editsPending;
	private short quality;
	private Date lastUpdated;

	public Release() {
	}

	public Release(int id, Serializable gid, String name, int artistCredit,
			int releaseGroup, String comment, int editsPending, short quality) {
		this.id = id;
		this.gid = gid;
		this.name = name;
		this.artistCredit = artistCredit;
		this.releaseGroup = releaseGroup;
		this.comment = comment;
		this.editsPending = editsPending;
		this.quality = quality;
	}

	public Release(int id, Serializable gid, String name, int artistCredit,
			int releaseGroup, Integer status, Integer packaging,
			Integer language, Integer script, String barcode, String comment,
			int editsPending, short quality, Date lastUpdated) {
		this.id = id;
		this.gid = gid;
		this.name = name;
		this.artistCredit = artistCredit;
		this.releaseGroup = releaseGroup;
		this.status = status;
		this.packaging = packaging;
		this.language = language;
		this.script = script;
		this.barcode = barcode;
		this.comment = comment;
		this.editsPending = editsPending;
		this.quality = quality;
		this.lastUpdated = lastUpdated;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Serializable getGid() {
		return this.gid;
	}

	public void setGid(Serializable gid) {
		this.gid = gid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getArtistCredit() {
		return this.artistCredit;
	}

	public void setArtistCredit(int artistCredit) {
		this.artistCredit = artistCredit;
	}

	public int getReleaseGroup() {
		return this.releaseGroup;
	}

	public void setReleaseGroup(int releaseGroup) {
		this.releaseGroup = releaseGroup;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getPackaging() {
		return this.packaging;
	}

	public void setPackaging(Integer packaging) {
		this.packaging = packaging;
	}

	public Integer getLanguage() {
		return this.language;
	}

	public void setLanguage(Integer language) {
		this.language = language;
	}

	public Integer getScript() {
		return this.script;
	}

	public void setScript(Integer script) {
		this.script = script;
	}

	public String getBarcode() {
		return this.barcode;
	}

	public void setBarcode(String barcode) {
		this.barcode = barcode;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public int getEditsPending() {
		return this.editsPending;
	}

	public void setEditsPending(int editsPending) {
		this.editsPending = editsPending;
	}

	public short getQuality() {
		return this.quality;
	}

	public void setQuality(short quality) {
		this.quality = quality;
	}

	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

}
