package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * ReleaseGroupSeries generated by hbm2java
 */
public class ReleaseGroupSeries implements java.io.Serializable {

	private ReleaseGroupSeriesId id;

	public ReleaseGroupSeries() {
	}

	public ReleaseGroupSeries(ReleaseGroupSeriesId id) {
		this.id = id;
	}

	public ReleaseGroupSeriesId getId() {
		return this.id;
	}

	public void setId(ReleaseGroupSeriesId id) {
		this.id = id;
	}

}
