package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * ReleaseEventId generated by hbm2java
 */
public class ReleaseEventId implements java.io.Serializable {

	private Integer release;
	private Short dateYear;
	private Short dateMonth;
	private Short dateDay;
	private Integer country;

	public ReleaseEventId() {
	}

	public ReleaseEventId(Integer release, Short dateYear, Short dateMonth,
			Short dateDay, Integer country) {
		this.release = release;
		this.dateYear = dateYear;
		this.dateMonth = dateMonth;
		this.dateDay = dateDay;
		this.country = country;
	}

	public Integer getRelease() {
		return this.release;
	}

	public void setRelease(Integer release) {
		this.release = release;
	}

	public Short getDateYear() {
		return this.dateYear;
	}

	public void setDateYear(Short dateYear) {
		this.dateYear = dateYear;
	}

	public Short getDateMonth() {
		return this.dateMonth;
	}

	public void setDateMonth(Short dateMonth) {
		this.dateMonth = dateMonth;
	}

	public Short getDateDay() {
		return this.dateDay;
	}

	public void setDateDay(Short dateDay) {
		this.dateDay = dateDay;
	}

	public Integer getCountry() {
		return this.country;
	}

	public void setCountry(Integer country) {
		this.country = country;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReleaseEventId))
			return false;
		ReleaseEventId castOther = (ReleaseEventId) other;

		return ((this.getRelease() == castOther.getRelease()) || (this
				.getRelease() != null && castOther.getRelease() != null && this
				.getRelease().equals(castOther.getRelease())))
				&& ((this.getDateYear() == castOther.getDateYear()) || (this
						.getDateYear() != null
						&& castOther.getDateYear() != null && this
						.getDateYear().equals(castOther.getDateYear())))
				&& ((this.getDateMonth() == castOther.getDateMonth()) || (this
						.getDateMonth() != null
						&& castOther.getDateMonth() != null && this
						.getDateMonth().equals(castOther.getDateMonth())))
				&& ((this.getDateDay() == castOther.getDateDay()) || (this
						.getDateDay() != null && castOther.getDateDay() != null && this
						.getDateDay().equals(castOther.getDateDay())))
				&& ((this.getCountry() == castOther.getCountry()) || (this
						.getCountry() != null && castOther.getCountry() != null && this
						.getCountry().equals(castOther.getCountry())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getRelease() == null ? 0 : this.getRelease().hashCode());
		result = 37 * result
				+ (getDateYear() == null ? 0 : this.getDateYear().hashCode());
		result = 37 * result
				+ (getDateMonth() == null ? 0 : this.getDateMonth().hashCode());
		result = 37 * result
				+ (getDateDay() == null ? 0 : this.getDateDay().hashCode());
		result = 37 * result
				+ (getCountry() == null ? 0 : this.getCountry().hashCode());
		return result;
	}

}
