package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * ReleaseTagRaw generated by hbm2java
 */
public class ReleaseTagRaw implements java.io.Serializable {

	private ReleaseTagRawId id;
	private boolean isUpvote;

	public ReleaseTagRaw() {
	}

	public ReleaseTagRaw(ReleaseTagRawId id, boolean isUpvote) {
		this.id = id;
		this.isUpvote = isUpvote;
	}

	public ReleaseTagRawId getId() {
		return this.id;
	}

	public void setId(ReleaseTagRawId id) {
		this.id = id;
	}

	public boolean isIsUpvote() {
		return this.isUpvote;
	}

	public void setIsUpvote(boolean isUpvote) {
		this.isUpvote = isUpvote;
	}

}
