package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ReplicationControl generated by hbm2java
 */
public class ReplicationControl implements java.io.Serializable {

	private int id;
	private int currentSchemaSequence;
	private Integer currentReplicationSequence;
	private Date lastReplicationDate;

	public ReplicationControl() {
	}

	public ReplicationControl(int id, int currentSchemaSequence) {
		this.id = id;
		this.currentSchemaSequence = currentSchemaSequence;
	}

	public ReplicationControl(int id, int currentSchemaSequence,
			Integer currentReplicationSequence, Date lastReplicationDate) {
		this.id = id;
		this.currentSchemaSequence = currentSchemaSequence;
		this.currentReplicationSequence = currentReplicationSequence;
		this.lastReplicationDate = lastReplicationDate;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getCurrentSchemaSequence() {
		return this.currentSchemaSequence;
	}

	public void setCurrentSchemaSequence(int currentSchemaSequence) {
		this.currentSchemaSequence = currentSchemaSequence;
	}

	public Integer getCurrentReplicationSequence() {
		return this.currentReplicationSequence;
	}

	public void setCurrentReplicationSequence(Integer currentReplicationSequence) {
		this.currentReplicationSequence = currentReplicationSequence;
	}

	public Date getLastReplicationDate() {
		return this.lastReplicationDate;
	}

	public void setLastReplicationDate(Date lastReplicationDate) {
		this.lastReplicationDate = lastReplicationDate;
	}

}
