package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * SeriesAnnotationId generated by hbm2java
 */
public class SeriesAnnotationId implements java.io.Serializable {

	private int series;
	private int annotation;

	public SeriesAnnotationId() {
	}

	public SeriesAnnotationId(int series, int annotation) {
		this.series = series;
		this.annotation = annotation;
	}

	public int getSeries() {
		return this.series;
	}

	public void setSeries(int series) {
		this.series = series;
	}

	public int getAnnotation() {
		return this.annotation;
	}

	public void setAnnotation(int annotation) {
		this.annotation = annotation;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SeriesAnnotationId))
			return false;
		SeriesAnnotationId castOther = (SeriesAnnotationId) other;

		return (this.getSeries() == castOther.getSeries())
				&& (this.getAnnotation() == castOther.getAnnotation());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSeries();
		result = 37 * result + this.getAnnotation();
		return result;
	}

}
