package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * SeriesTagRaw generated by hbm2java
 */
public class SeriesTagRaw implements java.io.Serializable {

	private SeriesTagRawId id;
	private boolean isUpvote;

	public SeriesTagRaw() {
	}

	public SeriesTagRaw(SeriesTagRawId id, boolean isUpvote) {
		this.id = id;
		this.isUpvote = isUpvote;
	}

	public SeriesTagRawId getId() {
		return this.id;
	}

	public void setId(SeriesTagRawId id) {
		this.id = id;
	}

	public boolean isIsUpvote() {
		return this.isUpvote;
	}

	public void setIsUpvote(boolean isUpvote) {
		this.isUpvote = isUpvote;
	}

}
