package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * Series generated by hbm2java
 */
public class Series implements java.io.Serializable {

	private int id;
	private Serializable gid;
	private String name;
	private String comment;
	private int type;
	private int orderingAttribute;
	private int orderingType;
	private int editsPending;
	private Date lastUpdated;

	public Series() {
	}

	public Series(int id, Serializable gid, String name, String comment,
			int type, int orderingAttribute, int orderingType, int editsPending) {
		this.id = id;
		this.gid = gid;
		this.name = name;
		this.comment = comment;
		this.type = type;
		this.orderingAttribute = orderingAttribute;
		this.orderingType = orderingType;
		this.editsPending = editsPending;
	}

	public Series(int id, Serializable gid, String name, String comment,
			int type, int orderingAttribute, int orderingType,
			int editsPending, Date lastUpdated) {
		this.id = id;
		this.gid = gid;
		this.name = name;
		this.comment = comment;
		this.type = type;
		this.orderingAttribute = orderingAttribute;
		this.orderingType = orderingType;
		this.editsPending = editsPending;
		this.lastUpdated = lastUpdated;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Serializable getGid() {
		return this.gid;
	}

	public void setGid(Serializable gid) {
		this.gid = gid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public int getOrderingAttribute() {
		return this.orderingAttribute;
	}

	public void setOrderingAttribute(int orderingAttribute) {
		this.orderingAttribute = orderingAttribute;
	}

	public int getOrderingType() {
		return this.orderingType;
	}

	public void setOrderingType(int orderingType) {
		this.orderingType = orderingType;
	}

	public int getEditsPending() {
		return this.editsPending;
	}

	public void setEditsPending(int editsPending) {
		this.editsPending = editsPending;
	}

	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

}
