package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * SeriesType generated by hbm2java
 */
public class SeriesType implements java.io.Serializable {

	private int id;
	private String name;
	private String entityType;
	private Integer parent;
	private int childOrder;
	private String description;

	public SeriesType() {
	}

	public SeriesType(int id, String name, String entityType, int childOrder) {
		this.id = id;
		this.name = name;
		this.entityType = entityType;
		this.childOrder = childOrder;
	}

	public SeriesType(int id, String name, String entityType, Integer parent,
			int childOrder, String description) {
		this.id = id;
		this.name = name;
		this.entityType = entityType;
		this.parent = parent;
		this.childOrder = childOrder;
		this.description = description;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEntityType() {
		return this.entityType;
	}

	public void setEntityType(String entityType) {
		this.entityType = entityType;
	}

	public Integer getParent() {
		return this.parent;
	}

	public void setParent(Integer parent) {
		this.parent = parent;
	}

	public int getChildOrder() {
		return this.childOrder;
	}

	public void setChildOrder(int childOrder) {
		this.childOrder = childOrder;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
