package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * SeriesTagId generated by hbm2java
 */
public class SeriesTagId implements java.io.Serializable {

	private int series;
	private int tag;

	public SeriesTagId() {
	}

	public SeriesTagId(int series, int tag) {
		this.series = series;
		this.tag = tag;
	}

	public int getSeries() {
		return this.series;
	}

	public void setSeries(int series) {
		this.series = series;
	}

	public int getTag() {
		return this.tag;
	}

	public void setTag(int tag) {
		this.tag = tag;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SeriesTagId))
			return false;
		SeriesTagId castOther = (SeriesTagId) other;

		return (this.getSeries() == castOther.getSeries())
				&& (this.getTag() == castOther.getTag());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSeries();
		result = 37 * result + this.getTag();
		return result;
	}

}
