package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * SeriesTagRawId generated by hbm2java
 */
public class SeriesTagRawId implements java.io.Serializable {

	private int series;
	private int editor;
	private int tag;

	public SeriesTagRawId() {
	}

	public SeriesTagRawId(int series, int editor, int tag) {
		this.series = series;
		this.editor = editor;
		this.tag = tag;
	}

	public int getSeries() {
		return this.series;
	}

	public void setSeries(int series) {
		this.series = series;
	}

	public int getEditor() {
		return this.editor;
	}

	public void setEditor(int editor) {
		this.editor = editor;
	}

	public int getTag() {
		return this.tag;
	}

	public void setTag(int tag) {
		this.tag = tag;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SeriesTagRawId))
			return false;
		SeriesTagRawId castOther = (SeriesTagRawId) other;

		return (this.getSeries() == castOther.getSeries())
				&& (this.getEditor() == castOther.getEditor())
				&& (this.getTag() == castOther.getTag());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSeries();
		result = 37 * result + this.getEditor();
		result = 37 * result + this.getTag();
		return result;
	}

}
