package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * SeriesAnnotation generated by hbm2java
 */
public class SeriesAnnotation implements java.io.Serializable {

	private SeriesAnnotationId id;

	public SeriesAnnotation() {
	}

	public SeriesAnnotation(SeriesAnnotationId id) {
		this.id = id;
	}

	public SeriesAnnotationId getId() {
		return this.id;
	}

	public void setId(SeriesAnnotationId id) {
		this.id = id;
	}

}
