package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * Tag generated by hbm2java
 */
public class Tag implements java.io.Serializable {

	private int id;
	private String name;
	private int refCount;

	public Tag() {
	}

	public Tag(int id, String name, int refCount) {
		this.id = id;
		this.name = name;
		this.refCount = refCount;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getRefCount() {
		return this.refCount;
	}

	public void setRefCount(int refCount) {
		this.refCount = refCount;
	}

}
