package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * TagRelationId generated by hbm2java
 */
public class TagRelationId implements java.io.Serializable {

	private int tag1;
	private int tag2;

	public TagRelationId() {
	}

	public TagRelationId(int tag1, int tag2) {
		this.tag1 = tag1;
		this.tag2 = tag2;
	}

	public int getTag1() {
		return this.tag1;
	}

	public void setTag1(int tag1) {
		this.tag1 = tag1;
	}

	public int getTag2() {
		return this.tag2;
	}

	public void setTag2(int tag2) {
		this.tag2 = tag2;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TagRelationId))
			return false;
		TagRelationId castOther = (TagRelationId) other;

		return (this.getTag1() == castOther.getTag1())
				&& (this.getTag2() == castOther.getTag2());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTag1();
		result = 37 * result + this.getTag2();
		return result;
	}

}
