package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TagRelation generated by hbm2java
 */
public class TagRelation implements java.io.Serializable {

	private TagRelationId id;
	private int weight;
	private Date lastUpdated;

	public TagRelation() {
	}

	public TagRelation(TagRelationId id, int weight) {
		this.id = id;
		this.weight = weight;
	}

	public TagRelation(TagRelationId id, int weight, Date lastUpdated) {
		this.id = id;
		this.weight = weight;
		this.lastUpdated = lastUpdated;
	}

	public TagRelationId getId() {
		return this.id;
	}

	public void setId(TagRelationId id) {
		this.id = id;
	}

	public int getWeight() {
		return this.weight;
	}

	public void setWeight(int weight) {
		this.weight = weight;
	}

	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

}
