package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * TrackRaw generated by hbm2java
 */
public class TrackRaw implements java.io.Serializable {

	private int id;
	private int release;
	private String title;
	private String artist;
	private int sequence;

	public TrackRaw() {
	}

	public TrackRaw(int id, int release, String title, int sequence) {
		this.id = id;
		this.release = release;
		this.title = title;
		this.sequence = sequence;
	}

	public TrackRaw(int id, int release, String title, String artist,
			int sequence) {
		this.id = id;
		this.release = release;
		this.title = title;
		this.artist = artist;
		this.sequence = sequence;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getRelease() {
		return this.release;
	}

	public void setRelease(int release) {
		this.release = release;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getArtist() {
		return this.artist;
	}

	public void setArtist(String artist) {
		this.artist = artist;
	}

	public int getSequence() {
		return this.sequence;
	}

	public void setSequence(int sequence) {
		this.sequence = sequence;
	}

}
