package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * Track generated by hbm2java
 */
public class Track implements java.io.Serializable {

	private int id;
	private Serializable gid;
	private int recording;
	private int medium;
	private int position;
	private String number;
	private String name;
	private int artistCredit;
	private Integer length;
	private int editsPending;
	private Date lastUpdated;
	private boolean isDataTrack;

	public Track() {
	}

	public Track(int id, Serializable gid, int recording, int medium,
			int position, String number, String name, int artistCredit,
			int editsPending, boolean isDataTrack) {
		this.id = id;
		this.gid = gid;
		this.recording = recording;
		this.medium = medium;
		this.position = position;
		this.number = number;
		this.name = name;
		this.artistCredit = artistCredit;
		this.editsPending = editsPending;
		this.isDataTrack = isDataTrack;
	}

	public Track(int id, Serializable gid, int recording, int medium,
			int position, String number, String name, int artistCredit,
			Integer length, int editsPending, Date lastUpdated,
			boolean isDataTrack) {
		this.id = id;
		this.gid = gid;
		this.recording = recording;
		this.medium = medium;
		this.position = position;
		this.number = number;
		this.name = name;
		this.artistCredit = artistCredit;
		this.length = length;
		this.editsPending = editsPending;
		this.lastUpdated = lastUpdated;
		this.isDataTrack = isDataTrack;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Serializable getGid() {
		return this.gid;
	}

	public void setGid(Serializable gid) {
		this.gid = gid;
	}

	public int getRecording() {
		return this.recording;
	}

	public void setRecording(int recording) {
		this.recording = recording;
	}

	public int getMedium() {
		return this.medium;
	}

	public void setMedium(int medium) {
		this.medium = medium;
	}

	public int getPosition() {
		return this.position;
	}

	public void setPosition(int position) {
		this.position = position;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getArtistCredit() {
		return this.artistCredit;
	}

	public void setArtistCredit(int artistCredit) {
		this.artistCredit = artistCredit;
	}

	public Integer getLength() {
		return this.length;
	}

	public void setLength(Integer length) {
		this.length = length;
	}

	public int getEditsPending() {
		return this.editsPending;
	}

	public void setEditsPending(int editsPending) {
		this.editsPending = editsPending;
	}

	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	public boolean isIsDataTrack() {
		return this.isDataTrack;
	}

	public void setIsDataTrack(boolean isDataTrack) {
		this.isDataTrack = isDataTrack;
	}

}
