package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Vote generated by hbm2java
 */
public class Vote implements java.io.Serializable {

	private int id;
	private int editor;
	private int edit;
	private short vote;
	private Date voteTime;
	private boolean superseded;

	public Vote() {
	}

	public Vote(int id, int editor, int edit, short vote, boolean superseded) {
		this.id = id;
		this.editor = editor;
		this.edit = edit;
		this.vote = vote;
		this.superseded = superseded;
	}

	public Vote(int id, int editor, int edit, short vote, Date voteTime,
			boolean superseded) {
		this.id = id;
		this.editor = editor;
		this.edit = edit;
		this.vote = vote;
		this.voteTime = voteTime;
		this.superseded = superseded;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getEditor() {
		return this.editor;
	}

	public void setEditor(int editor) {
		this.editor = editor;
	}

	public int getEdit() {
		return this.edit;
	}

	public void setEdit(int edit) {
		this.edit = edit;
	}

	public short getVote() {
		return this.vote;
	}

	public void setVote(short vote) {
		this.vote = vote;
	}

	public Date getVoteTime() {
		return this.voteTime;
	}

	public void setVoteTime(Date voteTime) {
		this.voteTime = voteTime;
	}

	public boolean isSuperseded() {
		return this.superseded;
	}

	public void setSuperseded(boolean superseded) {
		this.superseded = superseded;
	}

}
