package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * WorkLastmod generated by hbm2java
 */
public class WorkLastmod implements java.io.Serializable {

	private int id;
	private Date lastModified;

	public WorkLastmod() {
	}

	public WorkLastmod(int id) {
		this.id = id;
	}

	public WorkLastmod(int id, Date lastModified) {
		this.id = id;
		this.lastModified = lastModified;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

}
