package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * WorkRatingRawId generated by hbm2java
 */
public class WorkRatingRawId implements java.io.Serializable {

	private int work;
	private int editor;

	public WorkRatingRawId() {
	}

	public WorkRatingRawId(int work, int editor) {
		this.work = work;
		this.editor = editor;
	}

	public int getWork() {
		return this.work;
	}

	public void setWork(int work) {
		this.work = work;
	}

	public int getEditor() {
		return this.editor;
	}

	public void setEditor(int editor) {
		this.editor = editor;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WorkRatingRawId))
			return false;
		WorkRatingRawId castOther = (WorkRatingRawId) other;

		return (this.getWork() == castOther.getWork())
				&& (this.getEditor() == castOther.getEditor());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getWork();
		result = 37 * result + this.getEditor();
		return result;
	}

}
