package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * WorkAnnotationId generated by hbm2java
 */
public class WorkAnnotationId implements java.io.Serializable {

	private int work;
	private int annotation;

	public WorkAnnotationId() {
	}

	public WorkAnnotationId(int work, int annotation) {
		this.work = work;
		this.annotation = annotation;
	}

	public int getWork() {
		return this.work;
	}

	public void setWork(int work) {
		this.work = work;
	}

	public int getAnnotation() {
		return this.annotation;
	}

	public void setAnnotation(int annotation) {
		this.annotation = annotation;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WorkAnnotationId))
			return false;
		WorkAnnotationId castOther = (WorkAnnotationId) other;

		return (this.getWork() == castOther.getWork())
				&& (this.getAnnotation() == castOther.getAnnotation());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getWork();
		result = 37 * result + this.getAnnotation();
		return result;
	}

}
