package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * WorkAnnotation generated by hbm2java
 */
public class WorkAnnotation implements java.io.Serializable {

	private WorkAnnotationId id;

	public WorkAnnotation() {
	}

	public WorkAnnotation(WorkAnnotationId id) {
		this.id = id;
	}

	public WorkAnnotationId getId() {
		return this.id;
	}

	public void setId(WorkAnnotationId id) {
		this.id = id;
	}

}
