package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * WorkTagRawId generated by hbm2java
 */
public class WorkTagRawId implements java.io.Serializable {

	private int work;
	private int editor;
	private int tag;

	public WorkTagRawId() {
	}

	public WorkTagRawId(int work, int editor, int tag) {
		this.work = work;
		this.editor = editor;
		this.tag = tag;
	}

	public int getWork() {
		return this.work;
	}

	public void setWork(int work) {
		this.work = work;
	}

	public int getEditor() {
		return this.editor;
	}

	public void setEditor(int editor) {
		this.editor = editor;
	}

	public int getTag() {
		return this.tag;
	}

	public void setTag(int tag) {
		this.tag = tag;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WorkTagRawId))
			return false;
		WorkTagRawId castOther = (WorkTagRawId) other;

		return (this.getWork() == castOther.getWork())
				&& (this.getEditor() == castOther.getEditor())
				&& (this.getTag() == castOther.getTag());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getWork();
		result = 37 * result + this.getEditor();
		result = 37 * result + this.getTag();
		return result;
	}

}
