package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * WorkAttributeType generated by hbm2java
 */
public class WorkAttributeType implements java.io.Serializable {

	private int id;
	private String name;
	private String comment;
	private boolean freeText;
	private Integer parent;
	private int childOrder;
	private String description;

	public WorkAttributeType() {
	}

	public WorkAttributeType(int id, String name, String comment,
			boolean freeText, int childOrder) {
		this.id = id;
		this.name = name;
		this.comment = comment;
		this.freeText = freeText;
		this.childOrder = childOrder;
	}

	public WorkAttributeType(int id, String name, String comment,
			boolean freeText, Integer parent, int childOrder, String description) {
		this.id = id;
		this.name = name;
		this.comment = comment;
		this.freeText = freeText;
		this.parent = parent;
		this.childOrder = childOrder;
		this.description = description;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public boolean isFreeText() {
		return this.freeText;
	}

	public void setFreeText(boolean freeText) {
		this.freeText = freeText;
	}

	public Integer getParent() {
		return this.parent;
	}

	public void setParent(Integer parent) {
		this.parent = parent;
	}

	public int getChildOrder() {
		return this.childOrder;
	}

	public void setChildOrder(int childOrder) {
		this.childOrder = childOrder;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
