package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * WorkSeries generated by hbm2java
 */
public class WorkSeries implements java.io.Serializable {

	private WorkSeriesId id;

	public WorkSeries() {
	}

	public WorkSeries(WorkSeriesId id) {
		this.id = id;
	}

	public WorkSeriesId getId() {
		return this.id;
	}

	public void setId(WorkSeriesId id) {
		this.id = id;
	}

}
