package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * WorkAttribute generated by hbm2java
 */
public class WorkAttribute implements java.io.Serializable {

	private int id;
	private int work;
	private int workAttributeType;
	private Integer workAttributeTypeAllowedValue;
	private String workAttributeText;

	public WorkAttribute() {
	}

	public WorkAttribute(int id, int work, int workAttributeType) {
		this.id = id;
		this.work = work;
		this.workAttributeType = workAttributeType;
	}

	public WorkAttribute(int id, int work, int workAttributeType,
			Integer workAttributeTypeAllowedValue, String workAttributeText) {
		this.id = id;
		this.work = work;
		this.workAttributeType = workAttributeType;
		this.workAttributeTypeAllowedValue = workAttributeTypeAllowedValue;
		this.workAttributeText = workAttributeText;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getWork() {
		return this.work;
	}

	public void setWork(int work) {
		this.work = work;
	}

	public int getWorkAttributeType() {
		return this.workAttributeType;
	}

	public void setWorkAttributeType(int workAttributeType) {
		this.workAttributeType = workAttributeType;
	}

	public Integer getWorkAttributeTypeAllowedValue() {
		return this.workAttributeTypeAllowedValue;
	}

	public void setWorkAttributeTypeAllowedValue(
			Integer workAttributeTypeAllowedValue) {
		this.workAttributeTypeAllowedValue = workAttributeTypeAllowedValue;
	}

	public String getWorkAttributeText() {
		return this.workAttributeText;
	}

	public void setWorkAttributeText(String workAttributeText) {
		this.workAttributeText = workAttributeText;
	}

}
