package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * WorkAttributeTypeAllowedValue generated by hbm2java
 */
public class WorkAttributeTypeAllowedValue implements java.io.Serializable {

	private int id;
	private int workAttributeType;
	private String value;
	private Integer parent;
	private int childOrder;
	private String description;

	public WorkAttributeTypeAllowedValue() {
	}

	public WorkAttributeTypeAllowedValue(int id, int workAttributeType,
			int childOrder) {
		this.id = id;
		this.workAttributeType = workAttributeType;
		this.childOrder = childOrder;
	}

	public WorkAttributeTypeAllowedValue(int id, int workAttributeType,
			String value, Integer parent, int childOrder, String description) {
		this.id = id;
		this.workAttributeType = workAttributeType;
		this.value = value;
		this.parent = parent;
		this.childOrder = childOrder;
		this.description = description;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getWorkAttributeType() {
		return this.workAttributeType;
	}

	public void setWorkAttributeType(int workAttributeType) {
		this.workAttributeType = workAttributeType;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public Integer getParent() {
		return this.parent;
	}

	public void setParent(Integer parent) {
		this.parent = parent;
	}

	public int getChildOrder() {
		return this.childOrder;
	}

	public void setChildOrder(int childOrder) {
		this.childOrder = childOrder;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
