package com.hubble.hubblebackend.postgressql.model;

// Generated Sep 7, 2015 5:12:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * WorkRatingRaw generated by hbm2java
 */
public class WorkRatingRaw implements java.io.Serializable {

	private WorkRatingRawId id;
	private short rating;

	public WorkRatingRaw() {
	}

	public WorkRatingRaw(WorkRatingRawId id, short rating) {
		this.id = id;
		this.rating = rating;
	}

	public WorkRatingRawId getId() {
		return this.id;
	}

	public void setId(WorkRatingRawId id) {
		this.id = id;
	}

	public short getRating() {
		return this.rating;
	}

	public void setRating(short rating) {
		this.rating = rating;
	}

}
